### ISSUE TITLE
can not use vpn when xposed is actived

### ISSUE THREAD

**Issue by bitliuxm** [rovo89/Xposed#127]
on both xposed-v79-sdk22-arm and xposed-v80-sdk80-arm.

below log shows:
```
E/ActivityThread( 5355): Activity app.openconnect.api.GrantPermissionsActivity has leaked IntentReceiver jp.tkgktyk.xposed.niwatori.ModActivity$1@fc7d713 that was originally registe
E/ActivityThread( 5355): android.app.IntentReceiverLeaked: Activity app.openconnect.api.GrantPermissionsActivity has leaked IntentReceiver jp.tkgktyk.xposed.niwatori.ModActivity$1@f
E/ActivityThread( 5355): |      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:904)
E/ActivityThread( 5355): |      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:705)
E/ActivityThread( 5355): |      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1674)
E/ActivityThread( 5355): |      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1654)
E/ActivityThread( 5355): |      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1648)
E/ActivityThread( 5355): |      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:495)
E/ActivityThread( 5355): |      at jp.tkgktyk.xposed.niwatori.ModActivity.registerReceiver(ModActivity.java:524)
E/ActivityThread( 5355): |      at jp.tkgktyk.xposed.niwatori.ModActivity.access$900(ModActivity.java:37)
E/ActivityThread( 5355): |      at jp.tkgktyk.xposed.niwatori.ModActivity$12.afterHookedMethod(ModActivity.java:402)
E/ActivityThread( 5355): |      at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:689)
E/ActivityThread( 5355): |      at android.app.Activity.onWindowFocusChanged(<Xposed>)
E/ActivityThread( 5355): |      at com.android.internal.policy.impl.PhoneWindow$DecorView.onWindowFocusChanged(PhoneWindow.java:3430)
E/ActivityThread( 5355): |      at android.view.View.dispatchWindowFocusChanged(View.java:8689)
E/ActivityThread( 5355): |      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1056)
E/ActivityThread( 5355): |      at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3290)
E/ActivityThread( 5355): |      at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread( 5355): |      at android.os.Looper.loop(Looper.java:135)
E/ActivityThread( 5355): |      at android.app.ActivityThread.main(ActivityThread.java:5294)
E/ActivityThread( 5355): |      at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread( 5355): |      at java.lang.reflect.Method.invoke(Method.java:372)
E/ActivityThread( 5355): |      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/ActivityThread( 5355): |      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/ActivityThread( 5355): |      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
```

**Comment by rovo89** [comment]
The log you posted shows two things:
- Some information about a memory leak (not a crash!)
- That you're using at least one module (jp.tkgktyk.xposed.niwatori = "Niwatori - One Handed Mode") which seems to be responsible for this.

Please disable all your modules and try again. If it still doesn't work, please provide a full logcat.

**Comment by rovo89** [comment]
Closed due to lack of response.
