### ISSUE TITLE
Didn't find class "com.example.lukakas.clock.Tutorial"

### ISSUE THREAD

**Issue by idlukakas** [rovo89/Xposed#157]
I can't follow development tutorial with build.gradle 2.10 version. I'm getting this error when reboot my Nexus 5 CM 13:

Didn't find class "com.example.lukakas.clock.Tutorial"

IDE:
Android Studio 2.1

build.gradle module app:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.example.lukakas.clock"
        minSdkVersion 23
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    provided 'de.robv.android.xposed:api:82'
}
```

build.gradle project:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
assets\xposed_init:
`com.example.lukakas.clock.Tutorial
`

AndroidManifest.xml:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.lukakas.clock">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <meta-data
            android:name="xposedmodule"
            android:value="true" />
        <meta-data
            android:name="xposeddescription"
            android:value="Easy example which makes the status bar clock red and adds a smiley" />
        <meta-data
            android:name="xposedminversion"
            android:value="50" />
    </application>
</manifest>

```

Tutorial.java:

```
package com.example.lukakas.clock;

/**
 * Created by lukakas on 5/13/2016.
 */
import android.widget.TextView;

import de.robv.android.xposed.IXposedHookLoadPackage;
import de.robv.android.xposed.XC_MethodHook;
import de.robv.android.xposed.XposedBridge;
import  de.robv.android.xposed.callbacks.XC_LoadPackage.LoadPackageParam;

import static de.robv.android.xposed.XposedHelpers.findAndHookMethod;

public class Tutorial implements IXposedHookLoadPackage {
    @Override
    public void handleLoadPackage(LoadPackageParam loadPackageParam) throws Throwable {
        if (!loadPackageParam.packageName.equals("com.android.systemui"))
            return;
        XposedBridge.log("We are in SystemUI");
        findAndHookMethod("com.android.systemui.statusbar.policy.Clock", loadPackageParam.classLoader, "updateClock", new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                TextView textView = (TextView) param.thisObject;
                textView.append(":)");
            }
        });
    }
}
```

Logcat:

```
05-13 17:26:15.753 15555-15555/com.Taptigo.Xposed.XNotifications I/Xposed: [Taptigo-XNotifications] PackageReceiver.onReceive, action: android.intent.action.PACKAGE_ADDED, package: com.example.lukakas.clock
05-13 17:28:11.542 13495-13495/de.robv.android.xposed.installer I/XposedInstaller: updating modules.list
05-13 17:29:05.739 16589-16589/? D/XposedStartupMarker: Current time: 1463171345, PID: 16589
05-13 17:29:05.740 16589-16589/? I/Xposed: -----------------
05-13 17:29:05.740 16589-16589/? I/Xposed: Starting Xposed version 84, compiled for SDK 23
05-13 17:29:05.740 16589-16589/? I/Xposed: Device: Nexus 5 CAF (LGE), Android version 6.0.1 (SDK 23)
05-13 17:29:05.740 16589-16589/? I/Xposed: ROM: cm_hammerheadcaf-userdebug 6.0.1 MOB30D c007468d67 test-keys
05-13 17:29:05.740 16589-16589/? I/Xposed: Build fingerprint: google/hammerhead/hammerhead:6.0.1/MOB30D/2704746:user/release-keys
05-13 17:29:05.740 16589-16589/? I/Xposed: Platform: armeabi-v7a, 32-bit binary, system server: yes
05-13 17:29:05.740 16589-16589/? I/Xposed: SELinux enabled: yes, enforcing: yes
05-13 17:29:06.751 16589-16589/? I/Xposed: -----------------
05-13 17:29:06.751 16589-16589/? I/Xposed: Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-13 17:29:06.851 16589-16589/? I/Xposed: Detected ART runtime
05-13 17:29:06.857 16589-16589/? I/Xposed: Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
05-13 17:29:06.980 16589-16589/? I/Xposed: Loading modules from /data/app/com.example.lukakas.clock-1/base.apk
05-13 17:29:07.106 16589-16589/? I/Xposed:   Loading class com.example.lukakas.clock.Tutorial
05-13 17:29:07.108 16589-16589/? E/Xposed: java.lang.ClassNotFoundException: Didn't find class "com.example.lukakas.clock.Tutorial" on path: DexPathList[[zip file "/data/app/com.example.lukakas.clock-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                               at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:497)
                                               at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:457)
                                               at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:122)
                                           	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.example.lukakas.clock.Tutorial" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                               		... 4 more
                                           		Suppressed: java.lang.ClassNotFoundException: com.example.lukakas.clock.Tutorial
                                               at java.lang.Class.classForName(Native Method)
                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                               			... 5 more
                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-13 17:30:44.064 21421-21421/? I/Xposed: [Taptigo-XNotifications] BootCompleteReceiver.onReceive
05-13 17:31:06.982 23131-23131/? I/Xposed: [Taptigo-XNotifications] SchedulerReadyReceiver.onReceive
```

**Comment by idlukakas** [comment]
All my modules are disabled only this test app is enabled.

**Comment by idlukakas** [comment]
I don't know if this help you or me: http://forum.xda-developers.com/showpost.php?p=66116181&postcount=171

**Comment by idlukakas** [comment]
With 1.5.0 gradle just works, weird.

```
05-13 17:31:06.982 23131-23131/? I/Xposed: [Taptigo-XNotifications] SchedulerReadyReceiver.onReceive
05-13 17:40:39.070 24513-24513/? I/Xposed: [Taptigo-XNotifications] PackageReceiver.onReceive, action: android.intent.action.PACKAGE_REMOVED, package: com.example.lukakas.clock
05-13 17:40:40.542 24464-24464/? I/XposedInstaller: updating modules.list
05-13 17:40:41.450 24513-24513/? I/Xposed: [Taptigo-XNotifications] PackageReceiver.onReceive, action: android.intent.action.PACKAGE_ADDED, package: com.example.lukakas.clock
05-13 17:40:43.302 24513-24513/? I/Xposed: [Taptigo-XNotifications] PackageReceiver.onReceive, action: android.intent.action.PACKAGE_REPLACED, package: com.example.lukakas.clock
05-13 18:08:34.035 29007-29007/? I/Xposed: [Taptigo-XNotifications] PackageReceiver.onReceive, action: android.intent.action.PACKAGE_REMOVED, package: com.example.lukakas.clock
05-13 18:08:35.479 28937-28937/de.robv.android.xposed.installer I/XposedInstaller: updating modules.list
05-13 18:08:36.298 29007-29007/com.Taptigo.Xposed.XNotifications I/Xposed: [Taptigo-XNotifications] PackageReceiver.onReceive, action: android.intent.action.PACKAGE_ADDED, package: com.example.lukakas.clock
05-13 18:08:38.106 29007-29007/com.Taptigo.Xposed.XNotifications I/Xposed: [Taptigo-XNotifications] PackageReceiver.onReceive, action: android.intent.action.PACKAGE_REPLACED, package: com.example.lukakas.clock
05-13 18:08:58.573 29788-29788/? D/XposedStartupMarker: Current time: 1463173738, PID: 29788
05-13 18:08:58.574 29788-29788/? I/Xposed: -----------------
05-13 18:08:58.574 29788-29788/? I/Xposed: Starting Xposed version 84, compiled for SDK 23
05-13 18:08:58.574 29788-29788/? I/Xposed: Device: Nexus 5 CAF (LGE), Android version 6.0.1 (SDK 23)
05-13 18:08:58.574 29788-29788/? I/Xposed: ROM: cm_hammerheadcaf-userdebug 6.0.1 MOB30D c007468d67 test-keys
05-13 18:08:58.574 29788-29788/? I/Xposed: Build fingerprint: google/hammerhead/hammerhead:6.0.1/MOB30D/2704746:user/release-keys
05-13 18:08:58.574 29788-29788/? I/Xposed: Platform: armeabi-v7a, 32-bit binary, system server: yes
05-13 18:08:58.574 29788-29788/? I/Xposed: SELinux enabled: yes, enforcing: yes
05-13 18:08:58.580 29788-29788/? I/Xposed: Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-13 18:08:58.714 29788-29788/? I/Xposed: Detected ART runtime
05-13 18:08:58.717 29788-29788/? I/Xposed: Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
05-13 18:08:58.831 29788-29788/? I/Xposed: Loading modules from /data/app/com.example.lukakas.clock-1/base.apk
05-13 18:08:58.965 29788-29788/? I/Xposed:   Loading class com.example.lukakas.clock.Tutorial
05-13 18:09:49.888 30301-30301/? I/Xposed: We are in SystemUI
```

But the 2.0.0 version is same issue.

**Comment by rovo89** [comment]
Could you please try to disable Instant Run in Android Studio?

**Comment by rovo89** [comment]
This was most likely caused by Instant Run, disabling it should fix the issue. There's also a clear error message with Xposed v85.

**Comment by jonwinters** [comment]
Thanks a lot  the same problem with me ,

**Comment by iGio90** [comment]
I leave my +1 for @rovo89 fix and instant run!

**Comment by rovo89** [comment]
My "fix" is to disable Xposed when Instant Run is used and warn the user/developer about it. It would be highly complicated to support the scenario, as Instant Run sets up custom class loaders, loads classes from split dex files, ... In order to access your classes, you'd bascially have to run the app, but that's not happening when it's loaded as a module, it just instantiates your module class.

**Comment by iGio90** [comment]
Just saying that i used xposed a lot in the past and i was in need to hook something yesterday. Didn't have this problem once till yesterday and google toke me there. I dont think is necessary to bring support for instant run btwn. Fine enough that disabling it will reach the goal. Keep up the good work
