### ISSUE TITLE
LEGO games crash when opening with Xposed installed

### ISSUE THREAD

**Issue by HR19** [rovo89/Xposed#206]
I have several LEGO games (7, I think).  When I install Xposed, even with no modules, the LEGO games crash immediately upon opening, except for one, which gets to the main screen, with a "Touch to continue" message, then crashes when you touch the screen.  Attached is the log from when I tried to open each one, as I figured the more data the better.  The moment I uninstall Xposed, the games work fine.  I've tried deleting and redowloading, and I've tried this on two different devices with the same results.  Here is the info on the two devices: 

Device (vendor and model): Samsung Galaxy Tab S 8.4, LeEco Le Pro3
ROM: CM13 (Android 6.0.1, Tab S), EUI (Android 6.0, Pro3)
Xposed version: 87
Things you have already tried to resolve it: I haven't any clue where to begin.
Steps to reproduce: Install Xposed, open LEGO app

The below log is from the Pro3.
[logcat.txt](https://github.com/rovo89/Xposed/files/674862/logcat.txt)

**Comment by rovo89** [comment]
The crashes look like this:
```
12-27 17:25:13.427 F/DEBUG   (  655): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-27 17:25:13.427 F/DEBUG   (  655): Build fingerprint: 'LeEco/ZL1_CN/le_zl1:6.0.1/WAXCNFN5902011181S/letv11180649:user/release-keys'
12-27 17:25:13.427 F/DEBUG   (  655): Revision: '0'
12-27 17:25:13.427 F/DEBUG   (  655): ABI: 'arm'
12-27 17:25:13.427 F/DEBUG   (  655): pid: 6802, tid: 6822, name: GLThread 74  >>> com.wb.goog.legobdc <<<
12-27 17:25:13.427 F/DEBUG   (  655): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
12-27 17:25:13.438 F/DEBUG   (  655): Abort message: 'Invalid address 0xd2ee3780 passed to free: value not allocated'
12-27 17:25:13.438 F/DEBUG   (  655):     r0 00000000  r1 00001aa6  r2 00000006  r3 f2af3978
12-27 17:25:13.438 F/DEBUG   (  655):     r4 f2af3980  r5 f2af3930  r6 00000000  r7 0000010c
12-27 17:25:13.438 F/DEBUG   (  655):     r8 f6fe5594  r9 d2e80180  sl 00000001  fp d2ee3780
12-27 17:25:13.438 F/DEBUG   (  655):     ip 00000006  sp f2af3118  lr f6fb013d  pc f6fb2538  cpsr 400f0010
12-27 17:25:13.441 F/DEBUG   (  655): 
12-27 17:25:13.441 F/DEBUG   (  655): backtrace:
12-27 17:25:13.441 F/DEBUG   (  655):     #00 pc 00042538  /system/lib/libc.so (tgkill+12)
12-27 17:25:13.441 F/DEBUG   (  655):     #01 pc 00040139  /system/lib/libc.so (pthread_kill+32)
12-27 17:25:13.441 F/DEBUG   (  655):     #02 pc 0001c793  /system/lib/libc.so (raise+10)
12-27 17:25:13.441 F/DEBUG   (  655):     #03 pc 00019951  /system/lib/libc.so (__libc_android_abort+34)
12-27 17:25:13.441 F/DEBUG   (  655):     #04 pc 0001750c  /system/lib/libc.so (abort+4)
12-27 17:25:13.441 F/DEBUG   (  655):     #05 pc 0001b3a9  /system/lib/libc.so (__libc_fatal+16)
12-27 17:25:13.441 F/DEBUG   (  655):     #06 pc 00055ae1  /system/lib/libc.so (ifree+188)
12-27 17:25:13.441 F/DEBUG   (  655):     #07 pc 00058f2d  /system/lib/libc.so (je_free+388)
12-27 17:25:13.441 F/DEBUG   (  655):     #08 pc 0000e7c7  /system/lib/libutils.so (_ZNK7android7RefBase9decStrongEPKv+50)
12-27 17:25:13.441 F/DEBUG   (  655):     #09 pc 00008fcd  /system/lib/libwilhelm.so
12-27 17:25:13.441 F/DEBUG   (  655):     #10 pc 000196bb  /system/lib/libwilhelm.so
12-27 17:25:13.441 F/DEBUG   (  655):     #11 pc 001cc7f8  /data/app/com.wb.goog.legobdc-1/lib/arm/libLEGO_SH1.so (_Z13fnaSound_Initv+976)
12-27 17:25:13.441 F/DEBUG   (  655):     #12 pc 00200254  /data/app/com.wb.goog.legobdc-1/lib/arm/libLEGO_SH1.so (_Z17geMain_InitFusionP12fnFUSIONINITj+192)
12-27 17:25:13.442 F/DEBUG   (  655):     #13 pc 001675c4  /data/app/com.wb.goog.legobdc-1/lib/arm/libLEGO_SH1.so (_Z15Main_InitFusionP12fnFUSIONINIT+8)
12-27 17:25:13.442 F/DEBUG   (  655):     #14 pc 001cbbc4  /data/app/com.wb.goog.legobdc-1/lib/arm/libLEGO_SH1.so (_Z12fnaMain_InitR12fnFUSIONINIT+164)
12-27 17:25:13.442 F/DEBUG   (  655):     #15 pc 000b3394  /data/app/com.wb.goog.legobdc-1/lib/arm/libLEGO_SH1.so (_Z15Fusion_OnceInitv+164)
12-27 17:25:13.442 F/DEBUG   (  655):     #16 pc 000b37a0  /data/app/com.wb.goog.legobdc-1/lib/arm/libLEGO_SH1.so (Java_com_wbgames_LEGOgame_GameGLSurfaceView_nativeResize+32)
12-27 17:25:13.442 F/DEBUG   (  655):     #17 pc 00a406c5  /data/app/com.wb.goog.legobdc-1/oat/arm/base.odex (offset 0x793000)
```

A few lines above, I see these errors:
```
12-27 17:25:13.222 W/System.err( 6802): java.lang.NoSuchFieldError: no "I" field "mEGLConfig" in class "Lcom/google/android/gles_jni/EGLConfigImpl;" or its superclasses
12-27 17:25:13.227 W/System.err( 6802): 	at com.wbgames.LEGOgame.GameGLSurfaceView.nativeInit(Native Method)
12-27 17:25:13.227 W/System.err( 6802): 	at com.wbgames.LEGOgame.GameGLSurfaceView.access$2700(GameGLSurfaceView.java:109)
12-27 17:25:13.227 W/System.err( 6802): 	at com.wbgames.LEGOgame.GameGLSurfaceView$Renderer.onSurfaceCreated(GameGLSurfaceView.java:1610)
12-27 17:25:13.227 W/System.err( 6802): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
12-27 17:25:13.227 W/System.err( 6802): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

```
12-27 17:25:13.318 E/Adreno-GSL( 5733): <ioctl_kgsl_device_getproperty:830>: Either IOCTL_KGSL_DEVICE_GETPROPERTY 16 unsupported by kernel or 4 bytes is the wrong size
12-27 17:25:13.325 E/AudioMixer(  662): AudioMixer::getTrackName out of available tracks
12-27 17:25:13.325 E/AudioFlinger(  662): no more track names available
12-27 17:25:13.325 E/AudioFlinger(  662): createTrack_l() initCheck failed -12; no control block?
12-27 17:25:13.325 E/AudioTrack( 6802): AudioFlinger could not create track, status: -12
12-27 17:25:13.325 E/libOpenSLES( 6802): AudioTrack::initCheck status 4294967284
12-27 17:25:13.326 F/libc    ( 6802): Invalid address 0xd2ee3780 passed to free: value not allocated
```

I assume you don't have any active modules for these tests, but could you also try to disable resource replacements (it's a setting in the installer)?
Additionally, could you please check if these errors also come up without Xposed?

**Comment by HR19** [comment]
Correct, no active modules.  I tried "Disable Resource Hooks," but it changed nothing.  The moment I uninstall Xposed Framework, the apps work fine.

**Comment by rovo89** [comment]
How about this?
> Additionally, could you please check if these errors also come up without Xposed?

**Comment by HR19** [comment]
Do you mean with the framework, but not the installer?  I mentioned in my original post and last reply that the apps function correctly the moment the framework is uninstalled (though I may have not been clear on that).

**Comment by rovo89** [comment]
No, I mean completely without Xposed. The apps work fine as you say,  it does the log show similar error messages as quoted above?

**Comment by AnClark** [comment]
Maybe XPosed Blacklist would help, I guess.

**Comment by frpnit** [comment]
@rovo89 I can confirm this issue since i do have some lego games on my TV Box and thus they won't open with xposed installed. Tested with a fresh framework install, so i have no module loaded or whatsoever.

I had a rooted Ouya before, and had no problems on xposed there. So, i believe it may be something related with those newer framework iterations.

Well, i've uploaded my logcats from Lego Jurassic World, one with and another without xposed installed. Reading as an ordinary user, i could see things happening with framework that doesn't appear on normal state - SELinux denials, linked folders not being found... and the crash far below. I'm using Apps2SD so my games are linked to USB-OTG media rather than being on internal memory.

I hope there is a solution to this, even if i could use a workaround. Hope my logcats can help to achieve solution.

Cheers!

[lego jurassic world log.txt](https://github.com/rovo89/Xposed/files/965769/lego.jurassic.world.log.txt)
[lego jurassic world xposed log.txt](https://github.com/rovo89/Xposed/files/965770/lego.jurassic.world.xposed.log.txt)
