### ISSUE TITLE
Boot Loop on LG G4 H815, Android 6

### ISSUE THREAD

**Issue by guillaume-uH57J9** [rovo89/Xposed#226]
Hi,

A boot loop occurs on the first boot after installing xposed-v76-sdk23-arm64.zip
TWRP was installed recently over the stock rom using twrp-3.0.2-1-h815.img

Following that, I powered it off by removing the battery, and made a logcat.txt on the next boot. There was a bootloop on the nextboot too, and it was captured in the log

[logcat.zip](https://github.com/rovo89/Xposed/files/949756/logcat.zip)

**Comment by guillaume-uH57J9** [comment]
Looks like there was a crash, here's the relevant part of the log:

```
--------- beginning of crash
04-23 15:42:07.469 E/AndroidRuntime( 1417): *** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-23 15:42:07.469 E/AndroidRuntime( 1417): java.lang.RuntimeException: Failed to start service com.android.server.UiModeManagerService: onStart threw an exception
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:111)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at com.android.server.SystemServer.startService_aroundBody10(SystemServer.java:608)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:608)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at com.android.server.SystemServer.run(SystemServer.java:287)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at com.android.server.SystemServer.main(SystemServer.java:185)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at java.lang.reflect.Method.invoke(Native Method)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
04-23 15:42:07.469 E/AndroidRuntime( 1417): Caused by: java.lang.RuntimeException: Unable to get provider com.android.providers.settings.SettingsProvider: java.lang.ClassNotFoundException: Didn't find class "com.android.providers.settings.SettingsProvider" on path: DexPathList[[zip file "/system/framework/com.lge.mdm.jar", zip file "/system/priv-app/LGSettingsProvider/LGSettingsProvider.apk"],nativeLibraryDirectories=[/system/priv-app/LGSettingsProvider/lib/arm64, /vendor/lib64, /system/lib64]]
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5244)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:4877)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2001)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at android.content.ContentResolver.acquireProvider(ContentResolver.java:1472)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at android.provider.Settings$NameValueCache.lazyGetProvider(Settings.java:1309)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:1367)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at android.provider.Settings$Secure.getStringForUser(Settings.java:4003)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at android.provider.Settings$Secure.getIntForUser(Settings.java:4073)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at android.provider.Settings$Secure.getInt(Settings.java:4063)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at com.android.server.UiModeManagerService.onStart(UiModeManagerService.java:187)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:109)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	... 8 more
04-23 15:42:07.469 E/AndroidRuntime( 1417): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.providers.settings.SettingsProvider" on path: DexPathList[[zip file "/system/framework/com.lge.mdm.jar", zip file "/system/priv-app/LGSettingsProvider/LGSettingsProvider.apk"],nativeLibraryDirectories=[/system/priv-app/LGSettingsProvider/lib/arm64, /vendor/lib64, /system/lib64]]
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5229)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	... 18 more
04-23 15:42:07.469 E/AndroidRuntime( 1417): 	Suppressed: java.io.IOException: Failed to open dex files from /system/priv-app/LGSettingsProvider/LGSettingsProvider.apk
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at dalvik.system.DexFile.openDexFileNative(Native Method)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at dalvik.system.DexFile.<init>(DexFile.java:80)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at dalvik.system.DexFile.<init>(DexFile.java:59)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:420)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at de.robv.android.xposed.XposedBridge$4.afterHookedMethod(XposedBridge.java:251)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:689)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at android.app.LoadedApk.<init>(<Xposed>)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1839)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1795)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1767)
04-23 15:42:07.469 E/AndroidRuntime( 1417): 		at android.app.ContextImpl.createPac
```

**Comment by guillaume-uH57J9** [comment]
I just realized xposed v76 is an old version sorry for that, will try with the latest and report back. 

Got confused when dowloading from http://dl-xda.xposed.info/framework/sdk23/arm64/
Took the first in the list, but that's actually the oldest because of the filename sorting
