### ISSUE TITLE
Cannot read/write SDcard in my Xposed module

### ISSUE THREAD

**Issue by lzq8272587** [rovo89/Xposed#227]
Hello everyone!

Recently I am using Xposed to log the inter-component calls such as startService/bindService in my Android device.

What I did is to write down a record in sdcard if startService() or bindSerivce() is called.

I can successfully hook the call, but when I try to read/write a new record in the sdcard, I always get the error:

05-01 16:20:20.609 1029-10028/? E/Xposed: java.io.FileNotFoundException: /data/local/tmp/log: open failed: EACCES (Permission denied)
                                              at libcore.io.IoBridge.open(IoBridge.java:452)
                                              at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                              at java.io.FileReader.<init>(FileReader.java:42)
                                              at com.netlab.actfreezer.SystemServiceHook$BindServiceContextHook.beforeHookedMethod(SystemServiceHook.java:327)
                                              at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
                                              at com.android.server.am.ActivityManagerService.bindService(<Xposed>)
                                              at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:985)
                                              at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2489)
                                              at android.os.Binder.execTransact(Binder.java:453)
                                           Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
                                              at libcore.io.Posix.open(Native Method)
                                              at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                              at libcore.io.IoBridge.open(IoBridge.java:438)
                                              at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                              at java.io.FileReader.<init>(FileReader.java:42) 
                                              at com.netlab.actfreezer.SystemServiceHook$BindServiceContextHook.beforeHookedMethod(SystemServiceHook.java:327) 
                                              at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314) 
                                              at com.android.server.am.ActivityManagerService.bindService(<Xposed>) 
                                              at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:985) 
                                              at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2489) 
                                              at android.os.Binder.execTransact(Binder.java:453) 

It seems that my Xposed module does not have the permission to read/write sdcard.

But I grant the storage permission in the Manifest of my Xposed module app, and also in the Xposed installer. My device is rooted, and the default setting in my Super SU is to grant root permission for any request.

How can I fix the problem? Thanks !!

**Comment by rovo89** [comment]
Please don't double-post: https://github.com/rovo89/XposedBridge/issues/168
