### ISSUE TITLE
Xposed bug with WebView

### ISSUE THREAD

**Issue by hamberluo** [rovo89/Xposed#234]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity 
android.view.InflateException: Binary XML file line #19: Binary XML file line #1: Error inflating class <unknown>
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6236)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by android.view.InflateException: Binary XML file line #19: Binary XML file line #1: Error inflating class <unknown>

Caused by android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:964)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
       at android.view.LayoutInflater.parseInclude(Unknown Source)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
       at android.view.LayoutInflater.inflate(Unknown Source)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
       at android.app.Activity.performCreate(Activity.java:6684)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6236)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by java.lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library.
       at android.support.design.widget.ThemeUtils.checkAppCompatTheme(ThemeUtils.java:33)
       at android.support.design.widget.AppBarLayout.(AppBarLayout.java)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:964)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
       at android.view.LayoutInflater.parseInclude(Unknown Source)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
       at android.view.LayoutInflater.inflate(Unknown Source)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
       at android.app.Activity.performCreate(Activity.java:6684)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6236)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by Massi-X** [comment]
What Xposed version are you using? It's a custom one? What Android version? Is this caused by some module? Have you tried to disable all modules? Full Xposed log?

**Comment by hamberluo** [comment]
This is the full xposed log I can upload from our users. I cannot submit more information.
This only happens at activity which has webview.

**Comment by hamberluo** [comment]
Another clue: these devices use MoKee rom.
[http://www.mokeedev.com/](http://www.mokeedev.com/)
