### ISSUE TITLE
Xposed is causing our App To Crash (Stacktrace from fabric)

### ISSUE THREAD

**Issue by jharman-homeadvisor** [rovo89/Xposed#239]
We are getting lots of these stack traces from our users using our app with xposedbridge installed. 

Os versions: 5,6

It's happening at this rate for various devices:
Device Manf. | % of crashes
------------ | -------------
samsung | 28%
asus | 27%
HUAWEI | 18%
OPPO | 9%
Other… | 18%

I don't have steps to reproduce.

Stack Trace.

```
Fatal Exception: java.lang.IllegalArgumentException: Bad stream type -100
       at android.os.Parcel.readException(Parcel.java:1469)
       at android.os.Parcel.readException(Parcel.java:1419)
       at android.media.IAudioService$Stub$Proxy.adjustSuggestedStreamVolume(IAudioService.java:936)
       at android.media.AudioManager.adjustSuggestedStreamVolume(AudioManager.java:658)
       at android.media.AudioManager.handleKeyDown(AudioManager.java:527)
       at com.android.internal.policy.impl.PhoneWindow.onKeyDown(PhoneWindow.java:1563)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1969)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3852)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3826)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3558)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3718)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2023)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1705)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1696)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2000)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:5021)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by rovo89** [comment]
Sorry, was on vacation.

What are the hints that make you think that the crash is *caused* by Xposed`? The only reference to it is far down in the stack trace, at the entry point of the system. It might be just conincidence that those crashes you checked where from users with Xposed installed, without it being the culprit itself.

What's your app, by the way? Are you dealing with audio streams there?

**Comment by jharman-homeadvisor** [comment]
Our app can be downloaded here: https://play.google.com/store/apps/details?id=com.servicemagic.consumer

We are not doing anything with audio streams in the app. 

I reported this because the only unusual thing I saw in the trace was the presence of XposedBridge AND we don't have similar stack traces with key event handling that don't include the XposedBridge.

**Comment by rovo89** [comment]
I can understand your approach, however knowing what Xposed does, I can't imagine how this crash could be caused by it, at least not by the framework itself. Maybe those users have installed a module that tweak something in that area.

The next step from my point of view is getting feedback from the affected users. You could ask them to disable Xposed temporarily and see if the crash still happens.

**Comment by Xorok** [comment]
You could ask them what modules they have installed and see if you can find a common culprit there.

**Comment by rovo89** [comment]
As mentioned above, I can't imagine how this would be an issue with Xposed. If you find any evidence that it is, please reopen.

**Comment by Xorok** [comment]
@jharman-homeadvisor
You could detect if Xposed is installed at startup of the app and show a popup in this case. Something like:

"Hello, we've detected that the Xposed framework is installed on this device. Certain Xposed modules have caused problems with our app in the past, so if you encounter any issues or crashes, please try disabling Xposed and its modules and see if the problem persists. You can contact us via the email listed at the bottom of our Google Play Store page."
"OK"

This way you might also be able to get in touch with users that can reproduce those crashes.
