### ISSUE TITLE
Constant zygote service not accessible errors. 

### ISSUE THREAD

**Issue by fjsferreira** [rovo89/Xposed#250]
This is what I get in stock oos, rooted with magisk, and stock kernel on the oneplus 5, xposed v88.1, but it was the same in v88.
I get this even with no modules :( any help? 

10-10 22:03:20.367 I/Xposed  (  852): -----------------
10-10 22:03:20.367 I/Xposed  (  852): Starting Xposed version 88.1, compiled for SDK 25
10-10 22:03:20.367 I/Xposed  (  852): Device: ONEPLUS A5000 (OnePlus), Android version 7.1.1 (SDK 25)
10-10 22:03:20.367 I/Xposed  (  852): ROM: ONEPLUS A5000_23_171006
10-10 22:03:20.367 I/Xposed  (  852): Build fingerprint: OnePlus/OnePlus5/OnePlus5:7.1.1/NMF26X/09131759:user/release-keys
10-10 22:03:20.367 I/Xposed  (  852): Platform: arm64-v8a, 64-bit binary, system server: yes
10-10 22:03:20.367 I/Xposed  (  852): SELinux enabled: yes, enforcing: yes
10-10 22:03:20.377 I/Xposed  (  852): -----------------
10-10 22:03:20.378 I/Xposed  (  852): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-10 22:03:30.449 I/Xposed  (  853): -----------------
10-10 22:03:30.449 I/Xposed  (  853): Starting Xposed version 88.1, compiled for SDK 25
10-10 22:03:30.449 I/Xposed  (  853): Device: ONEPLUS A5000 (OnePlus), Android version 7.1.1 (SDK 25)
10-10 22:03:30.449 I/Xposed  (  853): ROM: ONEPLUS A5000_23_171006
10-10 22:03:30.449 I/Xposed  (  853): Build fingerprint: OnePlus/OnePlus5/OnePlus5:7.1.1/NMF26X/09131759:user/release-keys
10-10 22:03:30.449 I/Xposed  (  853): Platform: arm64-v8a, 32-bit binary, system server: no
10-10 22:03:30.449 I/Xposed  (  853): SELinux enabled: yes, enforcing: yes
10-10 22:03:30.468 I/Xposed  (  853): -----------------
10-10 22:03:30.468 I/Xposed  (  853): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-10 22:03:31.003 I/Xposed  (  853): Detected ART runtime
10-10 22:03:31.015 I/Xposed  (  853): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-10 22:03:31.322 I/Xposed  (  853): Loading modules from /data/app/com.ihelp101.instagram-1/base.apk
10-10 22:03:31.344 I/Xposed  (  853):   Loading class com.ihelp101.instagram.Module
10-10 22:03:31.362 I/Xposed  (  853): Loading modules from /data/app/com.elesbb.xposedinputautocorrectalways-1/base.apk
10-10 22:03:31.445 I/Xposed  (  853):   Loading class com.elesbb.xposedinputautocorrectalways.XposedStuff
10-10 22:03:31.451 I/Xposed  (  853): Loading modules from /data/app/de.robv.android.xposed.mods.appsettings-1/base.apk
10-10 22:03:31.464 I/Xposed  (  853):   Loading class de.robv.android.xposed.mods.appsettings.XposedMod
10-10 22:03:31.473 E/Xposed  (  853): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow.DecorView
10-10 22:03:31.473 E/Xposed  (  853): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
10-10 22:03:31.473 E/Xposed  (  853): 	at de.robv.android.xposed.XposedHelpers.getParameterClasses(XposedHelpers.java:508)
10-10 22:03:31.473 E/Xposed  (  853): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
10-10 22:03:31.473 E/Xposed  (  853): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:258)
10-10 22:03:31.473 E/Xposed  (  853): 	at de.robv.android.xposed.mods.appsettings.hooks.Activities.hookActivitySettings(Activities.java:49)
10-10 22:03:31.473 E/Xposed  (  853): 	at de.robv.android.xposed.mods.appsettings.XposedMod.initZygote(XposedMod.java:234)
10-10 22:03:31.473 E/Xposed  (  853): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:509)
10-10 22:03:31.473 E/Xposed  (  853): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:423)
10-10 22:03:31.473 E/Xposed  (  853): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:92)
10-10 22:03:31.473 E/Xposed  (  853): Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow.DecorView
10-10 22:03:31.473 E/Xposed  (  853): 	at java.lang.Class.classForName(Native Method)
10-10 22:03:31.473 E/Xposed  (  853): 	at java.lang.Class.forName(Class.java:400)
10-10 22:03:31.473 E/Xposed  (  853): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
10-10 22:03:31.473 E/Xposed  (  853): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:67)
10-10 22:03:31.473 E/Xposed  (  853): 	... 8 more
10-10 22:03:31.473 E/Xposed  (  853): Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow.DecorView
10-10 22:03:31.473 E/Xposed  (  853): 	at java.lang.Class.classForName(Native Method)
10-10 22:03:31.473 E/Xposed  (  853): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
10-10 22:03:31.473 E/Xposed  (  853): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
10-10 22:03:31.473 E/Xposed  (  853): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-10 22:03:31.473 E/Xposed  (  853): 	... 12 more
10-10 22:03:31.473 E/Xposed  (  853): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
10-10 22:03:32.928 I/Xposed  (  852): Detected ART runtime
10-10 22:03:32.931 I/Xposed  (  852): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-10 22:03:33.305 I/Xposed  (  852): Loading modules from /data/app/com.ihelp101.instagram-1/base.apk
10-10 22:03:33.328 I/Xposed  (  852):   Loading class com.ihelp101.instagram.Module
10-10 22:03:33.358 I/Xposed  (  852): Loading modules from /data/app/com.elesbb.xposedinputautocorrectalways-1/base.apk
10-10 22:03:33.429 I/Xposed  (  852):   Loading class com.elesbb.xposedinputautocorrectalways.XposedStuff
10-10 22:03:33.433 I/Xposed  (  852): Loading modules from /data/app/de.robv.android.xposed.mods.appsettings-1/base.apk
10-10 22:03:33.445 I/Xposed  (  852):   Loading class de.robv.android.xposed.mods.appsettings.XposedMod
10-10 22:03:33.455 E/Xposed  (  852): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow.DecorView
10-10 22:03:33.455 E/Xposed  (  852): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
10-10 22:03:33.455 E/Xposed  (  852): 	at de.robv.android.xposed.XposedHelpers.getParameterClasses(XposedHelpers.java:508)
10-10 22:03:33.455 E/Xposed  (  852): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
10-10 22:03:33.455 E/Xposed  (  852): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:258)
10-10 22:03:33.455 E/Xposed  (  852): 	at de.robv.android.xposed.mods.appsettings.hooks.Activities.hookActivitySettings(Activities.java:49)
10-10 22:03:33.455 E/Xposed  (  852): 	at de.robv.android.xposed.mods.appsettings.XposedMod.initZygote(XposedMod.java:234)
10-10 22:03:33.455 E/Xposed  (  852): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:509)
10-10 22:03:33.455 E/Xposed  (  852): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:423)
10-10 22:03:33.455 E/Xposed  (  852): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:92)
10-10 22:03:33.455 E/Xposed  (  852): Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow.DecorView
10-10 22:03:33.455 E/Xposed  (  852): 	at java.lang.Class.classForName(Native Method)
10-10 22:03:33.455 E/Xposed  (  852): 	at java.lang.Class.forName(Class.java:400)
10-10 22:03:33.455 E/Xposed  (  852): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
10-10 22:03:33.455 E/Xposed  (  852): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:67)
10-10 22:03:33.455 E/Xposed  (  852): 	... 8 more
10-10 22:03:33.455 E/Xposed  (  852): Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow.DecorView
10-10 22:03:33.455 E/Xposed  (  852): 	at java.lang.Class.classForName(Native Method)
10-10 22:03:33.455 E/Xposed  (  852): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
10-10 22:03:33.455 E/Xposed  (  852): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
10-10 22:03:33.455 E/Xposed  (  852): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-10 22:03:33.455 E/Xposed  (  852): 	... 12 more
10-10 22:03:33.455 E/Xposed  (  852): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
10-10 22:04:04.269 E/Xposed  ( 4842): Zygote service is not accessible from PID 4842, UID 10097
10-10 22:04:04.278 E/Xposed  ( 4842): Zygote service is not accessible from PID 4842, UID 10097
10-10 22:04:04.279 E/Xposed  ( 4842): Zygote service is not accessible from PID 4842, UID 10097
10-10 22:04:04.280 E/Xposed  ( 4842): Zygote service is not accessible from PID 4842, UID 10097
10-10 22:04:05.330 E/Xposed  ( 4999): Zygote service is not accessible from PID 4999, UID 10067
10-10 22:04:05.340 E/Xposed  ( 4999): Zygote service is not accessible from PID 4999, UID 10067
10-10 22:04:05.342 E/Xposed  ( 4999): Zygote service is not accessible from PID 4999, UID 10067
10-10 22:04:05.343 E/Xposed  ( 4999): Zygote service is not accessible from PID 4999, UID 10067
10-10 22:04:06.389 E/Xposed  ( 5160): Zygote service is not accessible from PID 5160, UID 10089
10-10 22:04:06.399 E/Xposed  ( 5160): Zygote service is not accessible from PID 5160, UID 10089
10-10 22:04:06.401 E/Xposed  ( 5160): Zygote service is not accessible from PID 5160, UID 10089
10-10 22:04:06.403 E/Xposed  ( 5160): Zygote service is not accessible from PID 5160, UID 10089
10-10 22:04:07.287 E/Xposed  ( 5283): Zygote service is not accessible from PID 5283, UID 10090
10-10 22:04:07.296 E/Xposed  ( 5283): Zygote service is not accessible from PID 5283, UID 10090
10-10 22:04:07.298 E/Xposed  ( 5283): Zygote service is not accessible from PID 5283, UID 10090
10-10 22:04:07.302 E/Xposed  ( 5283): Zygote service is not accessible from PID 5283, UID 10090
10-10 22:04:08.274 E/Xposed  ( 5406): Zygote service is not accessible from PID 5406, UID 10016
10-10 22:04:08.284 E/Xposed  ( 5406): Zygote service is not accessible from PID 5406, UID 10016
10-10 22:04:08.285 E/Xposed  ( 5406): Zygote service is not accessible from PID 5406, UID 10016
10-10 22:04:08.286 E/Xposed  ( 5406): Zygote service is not accessible from PID 5406, UID 10016
10-10 22:04:09.585 E/Xposed  ( 5524): Zygote service is not accessible from PID 5524, UID 10020
10-10 22:04:09.594 E/Xposed  ( 5524): Zygote service is not accessible from PID 5524, UID 10020
10-10 22:04:09.595 E/Xposed  ( 5524): Zygote service is not accessible from PID 5524, UID 10020
10-10 22:04:09.596 E/Xposed  ( 5524): Zygote service is not accessible from PID 5524, UID 10020
10-10 22:04:12.294 E/Xposed  ( 5760): Zygote service is not accessible from PID 5760, UID 10095
10-10 22:04:12.296 E/Xposed  ( 5760): Zygote service is not accessible from PID 5760, UID 10095
10-10 22:04:12.308 E/Xposed  ( 5760): Zygote service is not accessible from PID 5760, UID 10095
10-10 22:04:12.310 E/Xposed  ( 5760): Zygote service is not accessible from PID 5760, UID 10095
10-10 22:04:13.290 E/Xposed  ( 5830): Zygote service is not accessible from PID 5830, UID 10096
10-10 22:04:13.291 E/Xposed  ( 5830): Zygote service is not accessible from PID 5830, UID 10096
10-10 22:04:13.299 E/Xposed  ( 5830): Zygote service is not accessible from PID 5830, UID 10096
10-10 22:04:13.301 E/Xposed  ( 5830): Zygote service is not accessible from PID 5830, UID 10096
10-10 22:04:14.276 E/Xposed  ( 5938): Zygote service is not accessible from PID 5938, UID 10092
10-10 22:04:14.287 E/Xposed  ( 5938): Zygote service is not accessible from PID 5938, UID 10092
10-10 22:04:14.289 E/Xposed  ( 5938): Zygote service is not accessible from PID 5938, UID 10092
10-10 22:04:14.291 E/Xposed  ( 5938): Zygote service is not accessible from PID 5938, UID 10092
10-10 22:04:15.262 E/Xposed  ( 6066): Zygote service is not accessible from PID 6066, UID 10098
10-10 22:04:15.264 E/Xposed  ( 6066): Zygote service is not accessible from PID 6066, UID 10098
10-10 22:04:15.273 E/Xposed  ( 6066): Zygote service is not accessible from PID 6066, UID 10098
10-10 22:04:15.276 E/Xposed  ( 6066): Zygote service is not accessible from PID 6066, UID 10098
10-10 22:04:16.268 E/Xposed  ( 6141): Zygote service is not accessible from PID 6141, UID 10091
10-10 22:04:16.269 E/Xposed  ( 6141): Zygote service is not accessible from PID 6141, UID 10091
10-10 22:04:16.278 E/Xposed  ( 6141): Zygote service is not accessible from PID 6141, UID 10091
10-10 22:04:16.279 E/Xposed  ( 6141): Zygote service is not accessible from PID 6141, UID 10091
10-10 22:04:18.755 E/Xposed  ( 6163): Zygote service is not accessible from PID 6163, UID 10016
10-10 22:04:18.756 E/Xposed  ( 6163): Zygote service is not accessible from PID 6163, UID 10016
10-10 22:04:18.766 E/Xposed  ( 6163): Zygote service is not accessible from PID 6163, UID 10016
10-10 22:04:18.768 E/Xposed  ( 6163): Zygote service is not accessible from PID 6163, UID 10016
10-10 22:04:32.865 E/Xposed  ( 7530): Zygote service is not accessible from PID 7530, UID 10110
10-10 22:04:32.867 E/Xposed  ( 7530): Zygote service is not accessible from PID 7530, UID 10110
10-10 22:04:32.878 E/Xposed  ( 7530): Zygote service is not accessible from PID 7530, UID 10110
10-10 22:04:32.880 E/Xposed  ( 7530): Zygote service is not accessible from PID 7530, UID 10110

**Comment by fjsferreira** [comment]
Correction:

The error doesn't show up with no modules. The error doesn't show up with some modules, like xinsta or latest gravity box. 
The error shows up with other modules like network speed indicator, minminguard, etc. 

This error seems to be specific to oos on the oneplus 5. Other lineage based rom's on the same device don't produce this error with the same modules that produce it on stock oos. 

Findings:this is not related to SELinux, I've tried enforcing or permissive. And it's not related to magisk version or system version of xposed, it happens in both. 
It's also not related to using magisk or supersu and using data encrypted or decrypted. So far, the only pattern i found is that the error is specific to stock oos and specific modules like the ones mentioned.

**Comment by HiFiPhile** [comment]
Hi, I also have this issue on my OnePlus3. Using magisk systemless xposed module 88.1.

**Comment by htfy96** [comment]
Still exist with v90 beta1 Magisk systemless on OP3 OxygenOS.

**Comment by mcdachpappe** [comment]
still exists on:
- op3t,
- stock oxygenos 5.0.5,
- magisk v17.1,

modules:
- gravitybox
- appops xposed
