### ISSUE TITLE
Honor 8 & xposed-v88.1-sdk24-arm64.zip - Xposed installed but cant be activated

### ISSUE THREAD

**Issue by oblus** [rovo89/Xposed#268]
Hi

on my rooted Honor 8 i've installed by TWRP xposed-v88.1-sdk24-arm64.zip 
and also tried by Xposed-Installer - Xposed installed but cant be activated,
also logs in installer are empty - i will attach logs from SystemLog app after reboot when installed from Xposed-Installer...

If its not enaught say what to do... 

what is done with my Honor 8: unlocked bootloader, updated from MM do N (sdk24) and rooted via XDA guide - my bluetooth ant't work properly - after I've permanently uninstall Instagram updates and disable this app my bluetooth now enabling but when its connecting to other device is diconnecting, also automatic synchronisation is broken - need to sync calendar manually
[2017-10-18_11.07.zip](https://github.com/rovo89/Xposed/files/1394094/2017-10-18_11.07.zip)
...

**Comment by rovo89** [comment]
```
10-18 11:03:31.978 E/Xposed  (  442): Errors during Xposed initialization
10-18 11:03:31.978 E/Xposed  (  442): java.io.IOException: Permission denied while reading /data/user_de/0/de.robv.android.xposed.installer/conf/modules.list
10-18 11:03:31.978 E/Xposed  (  442): 	at de.robv.android.xposed.services.ZygoteService.readFile(Native Method)
10-18 11:03:31.978 E/Xposed  (  442): 	at de.robv.android.xposed.services.BaseService.getFileInputStream(BaseService.java:132)
10-18 11:03:31.978 E/Xposed  (  442): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:419)
10-18 11:03:31.978 E/Xposed  (  442): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:92)
```

Please try reinstalling the latest Xposed Installer. If that doesn't help, please execute these commands and post the output:
```
ls -lZ /data/user_de/0/de.robv.android.xposed.installer/conf/modules.list
ls -ldZ /data/user_de/0/de.robv.android.xposed.installer/conf/
ls -ldZ /data/user_de/0/de.robv.android.xposed.installer/
ls -ldZ /data/user_de/0/
ls -ldZ /data/user_de/
ls -ldZ /data/
```

**Comment by jozein** [comment]
The permission of folder /data/user_de/0/de.robv.android.xposed.installer/ alwways restored 700 after next reboot on hwawei(honor) emui5, even if it was set as 751.

I am a module developer.  The same problem of my module. I tryed to downgrade the target SDK to 23. It works well. But so many people can't get update on google play store. How can I fix it?

**Comment by rovo89** [comment]
@jozein I tried to implement some changes which would allow Xposed to work even with 700, but that requires so many other changes that I probably won't be able to do it. Could you find out when exactly the permissions are reverted? Maybe I could hook the function which is responsible for this.

**Comment by jozein** [comment]
@rovo89 Sorry, I can't find it. I don't have the source code and device. My module works well after I downgraded the target sdk to 23.

**Comment by rovo89** [comment]
@jozein Thanks to @wanam, I found a way to let Xposed work even if /data/user_de/0/de.robv.android.xposed.installer has mode 0700. It's part of v89, so please give it a try. Note that this only helps to read the module list and write the log file. If any modules are suffering from the same issues while reading their own files, they're out of luck.

**Comment by haiyang1994** [comment]
have the same issue with my huawei honor 8, v89.

/data/user_de/0/de.robv.android.xposed.installer/ alwways restored to 700 after next reboot.

btw, i have tried success one time, but fail in the other time.

**Comment by haiyang1994** [comment]
find a solution! need to chmod /data/user_de/0/de.robv.android.xposed.installer everytime when u try to reboot.
