### ISSUE TITLE
xposed oreo x86 bootloops

### ISSUE THREAD

**Issue by youling257** [rovo89/Xposed#319]
[log.txt](https://github.com/rovo89/Xposed/files/1654845/log.txt)

**Comment by youling257** [comment]
xposed-v90-sdk27-x86-beta3，bootloops
[log.txt](https://github.com/rovo89/Xposed/files/1684587/log.txt)

**Comment by youling257** [comment]
anybody see the log ?

**Comment by rovo89** [comment]
Yep.

```
02-01 15:34:27.126  2259  2259 W dex2oat : 'verify-at-runtime' is an obsolete compiler filter name that will be removed in future releases, please use 'extract' instead.
```

```
02-01 15:35:06.404  2212  2212 E Zygote  : System zygote died with exception
02-01 15:35:06.404  2212  2212 E Zygote  : java.lang.RuntimeException: ANDROID_SOCKET_zygote unset or invalid
02-01 15:35:06.404  2212  2212 E Zygote  : 	at com.android.internal.os.ZygoteServer.registerServerSocket(ZygoteServer.java:74)
02-01 15:35:06.404  2212  2212 E Zygote  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:748)
02-01 15:35:06.404  2212  2212 E Zygote  : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
02-01 15:35:06.404  2212  2212 E Zygote  : Caused by: java.lang.NumberFormatException: s == null
02-01 15:35:06.404  2212  2212 E Zygote  : 	at java.lang.Integer.parseInt(Integer.java:570)
02-01 15:35:06.404  2212  2212 E Zygote  : 	at java.lang.Integer.parseInt(Integer.java:643)
02-01 15:35:06.404  2212  2212 E Zygote  : 	at com.android.internal.os.ZygoteServer.registerServerSocket(ZygoteServer.java:72)
```

I don't think this is caused by Xposed, but by a misconfigured ROM. It's an "eng" build, which is usually used only during development, not for productive use.
