### ISSUE TITLE
Issue with Enforcing SELinux

### ISSUE THREAD

**Issue by System1c** [rovo89/Xposed#346]
Having this issue with v90-Beta3. "Xposed is installed but not active"

02-19 12:33:24.347 I/Xposed  (  921): -----------------
02-19 12:33:24.347 I/Xposed  (  921): Starting Xposed version 90.1-beta3 (Systemless), compiled for SDK 26
02-19 12:33:24.347 I/Xposed  (  921): Device: ONEPLUS A3010 (OnePlus), Android version 8.0.0 (SDK 26)
02-19 12:33:24.347 I/Xposed  (  921): ROM: ONEPLUS A3010_28_180309
02-19 12:33:24.347 I/Xposed  (  921): Build fingerprint: OnePlus/OnePlus3/OnePlus3T:8.0.0/OPR1.170623.032/02281230:user/release-keys
02-19 12:33:24.347 I/Xposed  (  921): Platform: arm64-v8a, 64-bit binary, system server: yes
02-19 12:33:24.347 I/Xposed  (  921): SELinux enabled: yes, enforcing: yes
02-19 12:33:24.371 I/Xposed  (  921): -----------------
02-19 12:33:24.371 I/Xposed  (  921): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-27 20:55:15.470 E/Xposed  (  921): Errors during Xposed initialization
03-27 20:55:15.470 E/Xposed  (  921): java.io.IOException: Permission denied while reading /data/user_de/0/de.robv.android.xposed.installer/conf/modules.list
03-27 20:55:15.470 E/Xposed  (  921): 	at de.robv.android.xposed.services.ZygoteService.readFile(Native Method)
03-27 20:55:15.470 E/Xposed  (  921): 	at de.robv.android.xposed.services.BaseService.getFileInputStream(BaseService.java:132)
03-27 20:55:15.470 E/Xposed  (  921): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:462)
03-27 20:55:15.470 E/Xposed  (  921): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:97)
03-27 20:55:22.693 I/Xposed  (  922): -----------------
03-27 20:55:22.694 I/Xposed  (  922): Starting Xposed version 90.1-beta3 (Systemless), compiled for SDK 26
03-27 20:55:22.694 I/Xposed  (  922): Device: ONEPLUS A3010 (OnePlus), Android version 8.0.0 (SDK 26)
03-27 20:55:22.694 I/Xposed  (  922): ROM: ONEPLUS A3010_28_180309
03-27 20:55:22.694 I/Xposed  (  922): Build fingerprint: OnePlus/OnePlus3/OnePlus3T:8.0.0/OPR1.170623.032/02281230:user/release-keys
03-27 20:55:22.694 I/Xposed  (  922): Platform: arm64-v8a, 32-bit binary, system server: no
03-27 20:55:22.694 I/Xposed  (  922): SELinux enabled: yes, enforcing: yes
03-27 20:55:22.698 I/Xposed  (  922): -----------------
03-27 20:55:22.699 I/Xposed  (  922): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-27 20:55:22.964 E/Xposed  (  922): Unable to open /vendor/framework/oat/arm to prepare apps for Xposed: Permission denied
03-27 20:55:24.711 I/Xposed  (  922): Detected ART runtime
03-27 20:55:24.714 I/Xposed  (  922): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
03-27 20:55:25.033 E/Xposed  (  922): Errors during Xposed initialization
03-27 20:55:25.033 E/Xposed  (  922): java.io.IOException: Permission denied while reading /data/user_de/0/de.robv.android.xposed.installer/conf/modules.list
03-27 20:55:25.033 E/Xposed  (  922): 	at de.robv.android.xposed.services.ZygoteService.readFile(Native Method)
03-27 20:55:25.033 E/Xposed  (  922): 	at de.robv.android.xposed.services.BaseService.getFileInputStream(BaseService.java:132)
03-27 20:55:25.033 E/Xposed  (  922): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:462)
03-27 20:55:25.033 E/Xposed  (  922): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:97)

**Comment by System1c** [comment]
OnePlus 3T running Open Beta 23. Problem only occurs on Enforcing SELinux.
