### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by oOtroyOo** [rovo89/Xposed#365]
100% crash when open Taobao APP. 

java.lang.RuntimeException: Unable to create application android.taobao.atlas.startup.AtlasBridgeApplication: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5531)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
at android.app.ActivityThread.handleBindApplication()
at android.app.ActivityThread.-wrap2(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6360)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at android.taobao.atlas.startup.AtlasBridgeApplication.onCreate(StubApplication.java:76)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5528)
... 12 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at android.taobao.atlas.startup.AtlasBridgeApplication.onCreate(StubApplication.java:73)
... 14 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at c8.pA.attachBaseContext(AtlasBridgeApplication.java)
at android.app.Application.attach(Application.java:194)
at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
at android.app.Instrumentation.newApplication(Instrumentation.java:993)
at com.ali.mobisecenhance.Init.run0(Init.java:280)
at com.ali.mobisecenhance.Init.run(Init.java:254)
at com.ali.mobisecenhance.ld.BridgeAppWrapper.onCreate(BridgeAppWrapper.java:222)
... 16 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at c8.pA._1invoke(AtlasBridgeApplication.java)
... 23 more
Caused by: java.lang.NullPointerException: Attempt to read from field 'boolean com.ali.mobisecenhance.ConfigInfo.isReaseMode' on a null object reference
at com.ali.mobisecenhance.ReflectMap.genRealName(ReflectMap.java:508)
at c8.iy._1forName(Hack.java)
at c8.iy.into(Hack.java)
at c8.by.allClasses(AtlasHacks.java)
at c8.by.defineAndVerify(AtlasHacks.java)
at c8.yx.attachBaseContext(BridgeApplicationDelegate.java:316)
... 25 more

**Comment by deadlineOvO** [comment]
我不会告诉你这是淘宝的热更新框架deXposed与Xposed有冲突的

**Comment by lihuibng** [comment]
> 我不会告诉你这是淘宝的热更新框架deXposed与Xposed有冲突的

怎么处理下啊

**Comment by deadlineOvO** [comment]
> > 我不会告诉你这是淘宝的热更新框架deXposed与Xposed有冲突的
> 
> 怎么处理下啊

关掉淘宝热更新咯
