### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by chenTest2013** [rovo89/Xposed#366]
android:7.0
phone:xiaomi mi 5s plus
arm64

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Application.getApplicationContext()' on a null object reference
	at me.piebridge.prevent.ui.a.a$1.replaceHookedMethod(AntiContactMod.java:24)
	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
	at android.content.ContentResolver.query(<Xposed>)
	at artf.a(:com.google.android.gms@12685025@12.6.85 (040408-197041431):30)
	at atwi.a(Unknown Source)
	at atwg.a(:com.google.android.gms@12685025@12.6.85 (040408-197041431):9)
	at atwg.c(:com.google.android.gms@12685025@12.6.85 (040408-197041431):4)
	at atwg.a(:com.google.android.gms@12685025@12.6.85 (040408-197041431):26)
	at oce.a(:com.google.android.gms@12685025@12.6.85 (040408-197041431):17)
	at nxz.uncaughtException(:com.google.android.gms@12685025@12.6.85 (040408-197041431):1)
	at nxz.uncaughtException(:com.google.android.gms@12685025@12.6.85 (040408-197041431):2)
	at nxz.uncaughtException(:com.google.android.gms@12685025@12.6.85 (040408-197041431):6)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)

**Comment by chenTest2013** [comment]
google play services is not start run
