### ISSUE TITLE
App crash report for v90.2-beta3 on Oreo

### ISSUE THREAD

**Issue by nicolas-yangli** [rovo89/Xposed#369]
Device: Nexus 5X
Framework version: v90.2-beta3
ROM version: 8.1.0 OPM6.171019.030.E1

App: https://play.google.com/store/apps/details?id=com.cmbchina.ccd.pluto.cmbActivity

The app crashs at launch if xposed framework is installed, even without any modules enabled. It was also reproducable on Marshmallow.

Logcat:

```
08-05 17:57:28.602  6682  6682 I System.out: getByteBufferValueById , destApk /data/app/com.cmbchina.ccd.pluto.cmbActivity-5YTR_mGMPDT07jPuxHHrCg==/base.apk IdValueMap = {1896449818=java.nio.HeapByteBuffer[pos=0 lim=964 cap=964], 305414945=java.nio.HeapByteBuffer[pos=0 lim=14 cap=14], 558253134=java.nio.HeapByteBuffer[pos=0 lim=172 cap=172]}
08-05 17:57:28.602  6682  6682 I System.out: getByteValueById , id = 305414945 , value = java.nio.HeapByteBuffer[pos=0 lim=14 cap=14]
08-05 17:57:29.062  6682  6682 D AndroidRuntime: Shutting down VM
08-05 17:57:29.063  6682  6682 E AndroidRuntime: FATAL EXCEPTION: main
08-05 17:57:29.063  6682  6682 E AndroidRuntime: Process: com.cmbchina.ccd.pluto.cmbActivity, PID: 6682
08-05 17:57:29.063  6682  6682 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.secneo.apkwrapper.ApplicationWrapper: java.lang.NullPointerException: Attempt to invoke virtual method 'com.cmbchina.ccd.library.cache.CacheManager$GlobalConfig com.cmbchina.ccd.library.cache.CacheManager$GlobalConfig.setSecureHelper(com.cmbchina.ccd.library.cache.base.ISecureHelper)' on a null object reference
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(<Xposed>)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
08-05 17:57:29.063  6682  6682 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.cmbchina.ccd.library.cache.CacheManager$GlobalConfig com.cmbchina.ccd.library.cache.CacheManager$GlobalConfig.setSecureHelper(com.cmbchina.ccd.library.cache.base.ISecureHelper)' on a null object reference
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at com.project.foundation.g.f(CMBAppLifeCycleManager.java:295)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at com.project.foundation.g.b(CMBAppLifeCycleManager.java:216)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at com.project.foundation.ProjectApplication.onCreate(ProjectApplication.java:50)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at com.cmbchina.ccd.pluto.cmbActivity.ShellApplication.onCreate(ShellApplication.java:31)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at com.secneo.apkwrapper.ApplicationWrapper.onCreate(ApplicationTemplate.java:47)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
08-05 17:57:29.063  6682  6682 E AndroidRuntime:        ... 12 more
08-05 17:57:29.080  3629  5934 W ActivityManager:   Force finishing activity com.cmbchina.ccd.pluto.cmbActivity/.SplashActivity
08-05 17:57:29.094  3629  4834 I ActivityManager: Showing crash dialog for package com.cmbchina.ccd.pluto.cmbActivity u0
```

**Comment by sidpagariya** [comment]
+1 I have the exact same crash for lots of apps...

**Comment by Jasi2169** [comment]
Galaxy s7 android oreo same issue with android.os.DeadObjectException @rovo89 my all apps start crashing one by one and immediately within seconds kind of so many popups this app crash that app crash and after reboot it works fine for some minutes and then issues comes again,the issue comes on January security update as well as latest august one as well

so xposed still not compatible with oreo
