### ISSUE TITLE
Issue on Motorola Moto G5s (XT1792), stock firmware (Android 8.1)

### ISSUE THREAD

**Issue by ShiroNoKarasu** [rovo89/Xposed#383]
Using Xposed on this firmware causes bootloops. Build number is OPP28.65-37 (recently released official firmware) and it has the 1 August security patch.

I've tried both system and system-less (Magisk) zips, all yield the same result. Uninstalling does bring things back to normal though.

Here's /data/user_de/0/de.robv.android.xposed.installer/error.log.old (error.log was blank):

05-16 03:38:39.766 I/Xposed  (  711): -----------------
05-16 03:38:39.766 I/Xposed  (  711): Starting Xposed version 90-beta3, compiled for SDK 27
05-16 03:38:39.766 I/Xposed  (  711): Device: Moto G (5S) (motorola), Android version 8.1.0 (SDK 27)
05-16 03:38:39.766 I/Xposed  (  711): ROM: n/a
05-16 03:38:39.766 I/Xposed  (  711): Build fingerprint: n/a
05-16 03:38:39.766 I/Xposed  (  711): Platform: armeabi-v7a, 32-bit binary, system server: yes
05-16 03:38:39.767 I/Xposed  (  711): SELinux enabled: yes, enforcing: yes
05-16 03:38:39.789 I/Xposed  (  711): -----------------
05-16 03:38:39.790 I/Xposed  (  711): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-20 18:43:18.846 E/Xposed  (  711): Unable to open /vendor/framework/oat/arm to prepare apps for Xposed: Permission denied
09-20 18:43:21.817 I/Xposed  (  711): Detected ART runtime
09-20 18:43:21.821 I/Xposed  (  711): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-20 18:43:22.367 E/Xposed  (  711): Errors during Xposed initialization
09-20 18:43:22.367 E/Xposed  (  711): java.lang.ExceptionInInitializerError
09-20 18:43:22.367 E/Xposed  (  711): 	at android.os.Build.-wrap2(Unknown Source:0)
09-20 18:43:22.367 E/Xposed  (  711): 	at android.os.Build$VERSION.<clinit>(Build.java:194)
09-20 18:43:22.367 E/Xposed  (  711): 	at android.content.res.ResourcesImpl.updateConfiguration(ResourcesImpl.java:445)
09-20 18:43:22.367 E/Xposed  (  711): 	at android.content.res.ResourcesImpl.<init>(ResourcesImpl.java:170)
09-20 18:43:22.367 E/Xposed  (  711): 	at android.content.res.Resources.<init>(Resources.java:247)
09-20 18:43:22.367 E/Xposed  (  711): 	at android.content.res.Resources.getSystem(Resources.java:180)
09-20 18:43:22.367 E/Xposed  (  711): 	at de.robv.android.xposed.XposedBridge.initXResources(XposedBridge.java:124)
09-20 18:43:22.367 E/Xposed  (  711): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:84)
09-20 18:43:22.367 E/Xposed  (  711): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
09-20 18:43:22.367 E/Xposed  (  711): 	at android.os.Build.getBuildNumber(Build.java:1145)
09-20 18:43:22.367 E/Xposed  (  711): 	at android.os.Build.deriveFingerprint(Build.java:826)
09-20 18:43:22.367 E/Xposed  (  711): 	at android.os.Build.<clinit>(Build.java:812)
09-20 18:43:22.367 E/Xposed  (  711): 	... 8 more

Does it have anything to do with the security patch?

Edit: I used Xposed version 90-beta3.

**Comment by scarlion1** [comment]
Did you ever find a solution?  I'm having bootloops too with 90-beta3 Android 8.1, but on a Moto G4.

**Comment by eebssk1** [comment]
Looks a SeLinux problem that makes XPosed unable to access some files.Since XPosed is no longer updated you'd better try other systemless solution.

**Comment by scarlion1** [comment]
@eebssk1 how else to get XPrivacy installed?

**Comment by eebssk1** [comment]
> 
> 
> @eebssk1 how else to get XPrivacy installed?

Well I remember that XPrivacy will crash system with original XPosed.Since i'm already using EdXposed i don't know how to solve that.
