### ISSUE TITLE
Error when modify package

### ISSUE THREAD

**Issue by devjava81** [rovo89/Xposed#387]
When rename XposedBrige package name and rebuild. I got error. Please tell me how to fix it
`10-26 16:49:05.984 2066-2066/? E/XUtils:   Cannot load module:com.android.system.framework.XUtils
      The Xposed API classes are compiled into the module's APK.
      This may cause strange issues and must be fixed by the module developer.
      For details, see: http://api.xposed.info/using.html
10-26 16:49:09.031 2494-2494/? A/art: art/runtime/runtime.cc:423]   native: #11 pc 000d3c75  /system/lib/libart.so (_ZN3art11ClassLinker11ResolveTypeERKNS_7DexFileEtNS_6HandleINS_6mirror8DexCacheEEENS4_INS5_11ClassLoaderEEE+132)
    art/runtime/runtime.cc:423]   native: #12 pc 000d35a5  /system/lib/libart.so (_ZN3art11ClassLinker13ResolveMethodILNS0_11ResolveModeE1EEEPNS_9ArtMethodERKNS_7DexFileEjNS_6HandleINS_6mirror8DexCacheEEENS8_INS9_11ClassLoaderEEES4_NS_10InvokeTypeE+128)
    art/runtime/runtime.cc:423]   native: #13 pc 001c93cf  /system/lib/libart.so (_ZN3art11ClassLinker13ResolveMethodILNS0_11ResolveModeE1EEEPNS_9ArtMethodEPNS_6ThreadEjS4_NS_10InvokeTypeE+154)
    art/runtime/runtime.cc:423]   native: #14 pc 003f7ccf  /system/lib/libart.so (artQuickResolutionTrampoline+886)
    art/runtime/runtime.cc:423]   native: #15 pc 000af413  /system/lib/libart.so (art_quick_resolution_trampoline+34)
    art/runtime/runtime.cc:423]   native: #16 pc 000476b3  /data/dalvik-cache/arm/system@framework@framework-common.jar@classes.dex (Java_com_android_system_framework_XposedInit_000245_afterHookedMethod__Lcom_android_system_framework_XC_1MethodHook_00024MethodHookParam_2+78)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XposedInit$5.afterHookedMethod(XposedInit.java:200)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.handleHookedMethod(XUtils.java:374)
    art/runtime/runtime.cc:423]   at android.app.LoadedApk.<init> [XposedHooked](<Xposed>:-2)
    art/runtime/runtime.cc:423]   at android.app.ContextImpl.createSystemContext(ContextImpl.java:1973)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.getSystemContext(ActivityThread.java:2074)
    art/runtime/runtime.cc:423]   - locked <0x0cc3f8d8> (a android.app.ActivityThread)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.attach(ActivityThread.java:6046)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.systemMain [XposedOriginal](ActivityThread.java:6099)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.invokeOriginalMethodNative!(Native method)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.handleHookedMethod(XUtils.java:360)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.systemMain [XposedHooked](<Xposed>:-2)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.createSystemContext(SystemServer.java:434)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.run(SystemServer.java:353)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.main(SystemServer.java:237)
    art/runtime/runtime.cc:423]   at java.lang.reflect.Method.invoke!(Native method)
    art/runtime/runtime.cc:423]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    art/runtime/runtime.cc:423]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.main(XUtils.java:102)
    art/runtime/runtime.cc:423] Dumping all threads without appropriate locks held: thread list lock
    art/runtime/runtime.cc:423] All threads:
    art/runtime/runtime.cc:423] DALVIK THREADS (8):
10-26 16:49:09.032 2494-2494/? A/art: art/runtime/runtime.cc:423] "main" prio=6 tid=1 Runnable
    art/runtime/runtime.cc:423]   | group="" sCount=0 dsCount=0 obj=0x74dae658 self=0xb3f05400
    art/runtime/runtime.cc:423]   | sysTid=2494 nice=-2 cgrp=default sched=0/0 handle=0xb6fa3534
    art/runtime/runtime.cc:423]   | state=R schedstat=( 436619687 30769533 165 ) utm=29 stm=13 core=1 HZ=100
    art/runtime/runtime.cc:423]   | stack=0xbe61a000-0xbe61c000 stackSize=8MB
    art/runtime/runtime.cc:423]   | held mutexes= "abort lock" "mutator lock"(shared held)
    art/runtime/runtime.cc:423]   native: #00 pc 00352a01  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
    art/runtime/runtime.cc:423]   native: #01 pc 003337f5  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+308)
    art/runtime/runtime.cc:423]   native: #02 pc 00345357  /system/lib/libart.so (_ZN3art14DumpCheckpoint3RunEPNS_6ThreadE+606)
    art/runtime/runtime.cc:423]   native: #03 pc 0033f635  /system/lib/libart.so (_ZN3art10ThreadList13RunCheckpointEPNS_7ClosureE+324)
    art/runtime/runtime.cc:423]   native: #04 pc 0033f337  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEb+586)
    art/runtime/runtime.cc:423]   native: #05 pc 003267e1  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+372)
    art/runtime/runtime.cc:423]   native: #06 pc 0031ae89  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+92)
    art/runtime/runtime.cc:423]   native: #07 pc 000b68c1  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1180)
    art/runtime/runtime.cc:423]   native: #08 pc 00135463  /system/lib/libart.so (_ZN3art21ClassDataItemIterator19ReadClassDataHeaderEv+194)
    art/runtime/runtime.cc:423]   native: #09 pc 000e856d  /system/lib/libart.so (_ZN3art11ClassLinker22LoadSuperAndInterfacesENS_6HandleINS_6mirror5ClassEEERKNS_7DexFileE+968)
    art/runtime/runtime.cc:423]   native: #10 pc 000e5d4b  /system/lib/libart.so (_ZN3art11ClassLinker11DefineClassEPNS_6ThreadEPKcjNS_6HandleINS_6mirror11ClassLoaderEEERKNS_7DexFileERKNS9_8ClassDefE+410)
    art/runtime/runtime.cc:423]   native: #11 pc 000e5a43  /system/lib/libart.so (_ZN3art11ClassLinker26FindClassInPathClassLoaderERNS_33ScopedObjectAccessAlreadyRunnableEPNS_6ThreadEPKcjNS_6HandleINS_6mirror11ClassLoaderEEEPPNS8_5ClassE+1002)
    art/runtime/runtime.cc:423]   native: #12 pc 000e6617  /system/lib/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+658)
    art/runtime/runtime.cc:423]   native: #13 pc 000d3c75  /system/lib/libart.so (_ZN3art11ClassLinker11ResolveTypeERKNS_7DexFileEtNS_6HandleINS_6mirror8DexCacheEEENS4_INS5_11ClassLoaderEEE+132)
    art/runtime/runtime.cc:423]   native: #14 pc 000d35a5  /system/lib/libart.so (_ZN3art11ClassLinker13ResolveMethodILNS0_11ResolveModeE1EEEPNS_9ArtMethodERKNS_7DexFileEjNS_6HandleINS_6mirror8DexCacheEEENS8_INS9_11ClassLoaderEEES4_NS_10InvokeTypeE+128)
    art/runtime/runtime.cc:423]   native: #15 pc 001c93cf  /system/lib/libart.so (_ZN3art11ClassLinker13ResolveMethodILNS0_11ResolveModeE1EEEPNS_9ArtMethodEPNS_6ThreadEjS4_NS_10InvokeTypeE+154)
    art/runtime/runtime.cc:423]   native: #16 pc 003f7ccf  /system/lib/libart.so (artQuickResolutionTrampoline+886)
    art/runtime/runtime.cc:423]   native: #17 pc 000af413  /system/lib/libart.so (art_quick_resolution_trampoline+34)
    art/runtime/runtime.cc:423]   native: #18 pc 000476b3  /data/dalvik-cache/arm/system@framework@framework-common.jar@classes.dex (Java_com_android_system_framework_XposedInit_000245_afterHookedMethod__Lcom_android_system_framework_XC_1MethodHook_00024MethodHookParam_2+78)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XposedInit$5.afterHookedMethod(XposedInit.java:200)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.handleHookedMethod(XUtils.java:374)
    art/runtime/runtime.cc:423]   at android.app.LoadedApk.<init> [XposedHooked](<Xposed>:-2)
    art/runtime/runtime.cc:423]   at android.app.ContextImpl.createSystemContext(ContextImpl.java:1973)
10-26 16:49:09.033 2494-2494/? A/art: art/runtime/runtime.cc:423]   at android.app.ActivityThread.getSystemContext(ActivityThread.java:2074)
    art/runtime/runtime.cc:423]   - locked <0x0cc3f8d8> (a android.app.ActivityThread)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.attach(ActivityThread.java:6046)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.systemMain [XposedOriginal](ActivityThread.java:6099)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.invokeOriginalMethodNative!(Native method)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.handleHookedMethod(XUtils.java:360)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.systemMain [XposedHooked](<Xposed>:-2)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.createSystemContext(SystemServer.java:434)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.run(SystemServer.java:353)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.main(SystemServer.java:237)
    art/runtime/runtime.cc:423]   at java.lang.reflect.Method.invoke!(Native method)
    art/runtime/runtime.cc:423]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    art/runtime/runtime.cc:423]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.main(XUtils.java:102)
    art/runtime/runtime.cc:423] 
    art/runtime/runtime.cc:423] "Signal Catcher" prio=6 tid=2 WaitingInMainSignalCatcherLoop
    art/runtime/runtime.cc:423]   | group="" sCount=1 dsCount=0 obj=0x12c070d0 self=0x7b816000
    art/runtime/runtime.cc:423]   | sysTid=2499 nice=0 cgrp=default sched=0/0 handle=0x83589920
    art/runtime/runtime.cc:423]   | state=S schedstat=( 1891250 0 3 ) utm=0 stm=0 core=2 HZ=100
    art/runtime/runtime.cc:423]   | stack=0x8348d000-0x8348f000 stackSize=1014KB
    art/runtime/runtime.cc:423]   | held mutexes=
    art/runtime/runtime.cc:423]   native: #00 pc 0004f3d4  /system/lib/libc.so (__rt_sigtimedwait+12)
    art/runtime/runtime.cc:423]   native: #01 pc 0001e923  /system/lib/libc.so (sigwait+34)
    art/runtime/runtime.cc:423]   native: #02 pc 0032996b  /system/lib/libart.so (_ZN3art9SignalSet4WaitEv+22)
    art/runtime/runtime.cc:423]   native: #03 pc 00329565  /system/lib/libart.so (_ZN3art13SignalCatcher13WaitForSignalEPNS_6ThreadERNS_9SignalSetE+168)
    art/runtime/runtime.cc:423]   native: #04 pc 00328365  /system/lib/libart.so (_ZN3art13SignalCatcher3RunEPv+276)
    art/runtime/runtime.cc:423]   native: #05 pc 0004da3f  /system/lib/libc.so (_ZL15__pthread_startPv+22)
10-26 16:49:13.714 2567-2567/? E/XUtils: /data/user_de/0/com.android.system.framework.installer/conf/modules.list
10-26 16:49:13.956 2567-2567/? E/XUtils:   Cannot load module:com.android.system.framework.XUtils
      The Xposed API classes are compiled into the module's APK.
      This may cause strange issues and must be fixed by the module developer.
      For details, see: http://api.xposed.info/using.html
10-26 16:49:16.237 2837-2837/? A/art: art/runtime/runtime.cc:423]   native: #06 pc 00135463  /system/lib/libart.so (_ZN3art21ClassDataItemIterator19ReadClassDataHeaderEv+194)
    art/runtime/runtime.cc:423]   native: #07 pc 000e856d  /system/lib/libart.so (_ZN3art11ClassLinker22LoadSuperAndInterfacesENS_6HandleINS_6mirror5ClassEEERKNS_7DexFileE+968)
    art/runtime/runtime.cc:423]   native: #08 pc 000e5d4b  /system/lib/libart.so (_ZN3art11ClassLinker11DefineClassEPNS_6ThreadEPKcjNS_6HandleINS_6mirror11ClassLoaderEEERKNS_7DexFileERKNS9_8ClassDefE+410)
    art/runtime/runtime.cc:423]   native: #09 pc 000e5a43  /system/lib/libart.so (_ZN3art11ClassLinker26FindClassInPathClassLoaderERNS_33ScopedObjectAccessAlreadyRunnableEPNS_6ThreadEPKcjNS_6HandleINS_6mirror11ClassLoaderEEEPPNS8_5ClassE+1002)
    art/runtime/runtime.cc:423]   native: #10 pc 000e6617  /system/lib/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+658)
    art/runtime/runtime.cc:423]   native: #11 pc 000d3c75  /system/lib/libart.so (_ZN3art11ClassLinker11ResolveTypeERKNS_7DexFileEtNS_6HandleINS_6mirror8DexCacheEEENS4_INS5_11ClassLoaderEEE+132)
    art/runtime/runtime.cc:423]   native: #12 pc 000d35a5  /system/lib/libart.so (_ZN3art11ClassLinker13ResolveMethodILNS0_11ResolveModeE1EEEPNS_9ArtMethodERKNS_7DexFileEjNS_6HandleINS_6mirror8DexCacheEEENS8_INS9_11ClassLoaderEEES4_NS_10InvokeTypeE+128)
    art/runtime/runtime.cc:423]   native: #13 pc 001c93cf  /system/lib/libart.so (_ZN3art11ClassLinker13ResolveMethodILNS0_11ResolveModeE1EEEPNS_9ArtMethodEPNS_6ThreadEjS4_NS_10InvokeTypeE+154)
    art/runtime/runtime.cc:423]   native: #14 pc 003f7ccf  /system/lib/libart.so (artQuickResolutionTrampoline+886)
    art/runtime/runtime.cc:423]   native: #15 pc 000af413  /system/lib/libart.so (art_quick_resolution_trampoline+34)
    art/runtime/runtime.cc:423]   native: #16 pc 000476b3  /data/dalvik-cache/arm/system@framework@framework-common.jar@classes.dex (Java_com_android_system_framework_XposedInit_000245_afterHookedMethod__Lcom_android_system_framework_XC_1MethodHook_00024MethodHookParam_2+78)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XposedInit$5.afterHookedMethod(XposedInit.java:200)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.handleHookedMethod(XUtils.java:374)
    art/runtime/runtime.cc:423]   at android.app.LoadedApk.<init> [XposedHooked](<Xposed>:-2)
    art/runtime/runtime.cc:423]   at android.app.ContextImpl.createSystemContext(ContextImpl.java:1973)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.getSystemContext(ActivityThread.java:2074)
    art/runtime/runtime.cc:423]   - locked <0x07b531e0> (a android.app.ActivityThread)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.attach(ActivityThread.java:6046)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.systemMain [XposedOriginal](ActivityThread.java:6099)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.invokeOriginalMethodNative!(Native method)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.handleHookedMethod(XUtils.java:360)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.systemMain [XposedHooked](<Xposed>:-2)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.createSystemContext(SystemServer.java:434)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.run(SystemServer.java:353)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.main(SystemServer.java:237)
    art/runtime/runtime.cc:423]   at java.lang.reflect.Method.invoke!(Native method)
    art/runtime/runtime.cc:423]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    art/runtime/runtime.cc:423]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.main(XUtils.java:102)
    art/runtime/runtime.cc:423] Dumping all threads without appropriate locks held: thread list lock
    art/runtime/runtime.cc:423] All threads:
    art/runtime/runtime.cc:423] DALVIK THREADS (8):
    art/runtime/runtime.cc:423] "main" prio=6 tid=1 Runnable
    art/runtime/runtime.cc:423]   | group="" sCount=0 dsCount=0 obj=0x74dae658 self=0xb3e85400
    art/runtime/runtime.cc:423]   | sysTid=2837 nice=-2 cgrp=default sched=0/0 handle=0xb6f65534
    art/runtime/runtime.cc:423]   | state=R schedstat=( 350854019 19397289 123 ) utm=22 stm=11 core=3 HZ=100
    art/runtime/runtime.cc:423]   | stack=0xbe746000-0xbe748000 stackSize=8MB
    art/runtime/runtime.cc:423]   | held mutexes= "abort lock" "mutator lock"(shared held)
10-26 16:49:16.238 2837-2837/? A/art: art/runtime/runtime.cc:423]   native: #00 pc 00352a01  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
    art/runtime/runtime.cc:423]   native: #01 pc 003337f5  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+308)
    art/runtime/runtime.cc:423]   native: #02 pc 00345357  /system/lib/libart.so (_ZN3art14DumpCheckpoint3RunEPNS_6ThreadE+606)
    art/runtime/runtime.cc:423]   native: #03 pc 0033f635  /system/lib/libart.so (_ZN3art10ThreadList13RunCheckpointEPNS_7ClosureE+324)
    art/runtime/runtime.cc:423]   native: #04 pc 0033f337  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEb+586)
    art/runtime/runtime.cc:423]   native: #05 pc 003267e1  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+372)
    art/runtime/runtime.cc:423]   native: #06 pc 0031ae89  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+92)
    art/runtime/runtime.cc:423]   native: #07 pc 000b68c1  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1180)
    art/runtime/runtime.cc:423]   native: #08 pc 00135463  /system/lib/libart.so (_ZN3art21ClassDataItemIterator19ReadClassDataHeaderEv+194)
    art/runtime/runtime.cc:423]   native: #09 pc 000e856d  /system/lib/libart.so (_ZN3art11ClassLinker22LoadSuperAndInterfacesENS_6HandleINS_6mirror5ClassEEERKNS_7DexFileE+968)
    art/runtime/runtime.cc:423]   native: #10 pc 000e5d4b  /system/lib/libart.so (_ZN3art11ClassLinker11DefineClassEPNS_6ThreadEPKcjNS_6HandleINS_6mirror11ClassLoaderEEERKNS_7DexFileERKNS9_8ClassDefE+410)
    art/runtime/runtime.cc:423]   native: #11 pc 000e5a43  /system/lib/libart.so (_ZN3art11ClassLinker26FindClassInPathClassLoaderERNS_33ScopedObjectAccessAlreadyRunnableEPNS_6ThreadEPKcjNS_6HandleINS_6mirror11ClassLoaderEEEPPNS8_5ClassE+1002)
    art/runtime/runtime.cc:423]   native: #12 pc 000e6617  /system/lib/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+658)
    art/runtime/runtime.cc:423]   native: #13 pc 000d3c75  /system/lib/libart.so (_ZN3art11ClassLinker11ResolveTypeERKNS_7DexFileEtNS_6HandleINS_6mirror8DexCacheEEENS4_INS5_11ClassLoaderEEE+132)
    art/runtime/runtime.cc:423]   native: #14 pc 000d35a5  /system/lib/libart.so (_ZN3art11ClassLinker13ResolveMethodILNS0_11ResolveModeE1EEEPNS_9ArtMethodERKNS_7DexFileEjNS_6HandleINS_6mirror8DexCacheEEENS8_INS9_11ClassLoaderEEES4_NS_10InvokeTypeE+128)
    art/runtime/runtime.cc:423]   native: #15 pc 001c93cf  /system/lib/libart.so (_ZN3art11ClassLinker13ResolveMethodILNS0_11ResolveModeE1EEEPNS_9ArtMethodEPNS_6ThreadEjS4_NS_10InvokeTypeE+154)
    art/runtime/runtime.cc:423]   native: #16 pc 003f7ccf  /system/lib/libart.so (artQuickResolutionTrampoline+886)
    art/runtime/runtime.cc:423]   native: #17 pc 000af413  /system/lib/libart.so (art_quick_resolution_trampoline+34)
    art/runtime/runtime.cc:423]   native: #18 pc 000476b3  /data/dalvik-cache/arm/system@framework@framework-common.jar@classes.dex (Java_com_android_system_framework_XposedInit_000245_afterHookedMethod__Lcom_android_system_framework_XC_1MethodHook_00024MethodHookParam_2+78)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XposedInit$5.afterHookedMethod(XposedInit.java:200)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.handleHookedMethod(XUtils.java:374)
    art/runtime/runtime.cc:423]   at android.app.LoadedApk.<init> [XposedHooked](<Xposed>:-2)
    art/runtime/runtime.cc:423]   at android.app.ContextImpl.createSystemContext(ContextImpl.java:1973)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.getSystemContext(ActivityThread.java:2074)
    art/runtime/runtime.cc:423]   - locked <0x07b531e0> (a android.app.ActivityThread)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.attach(ActivityThread.java:6046)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.systemMain [XposedOriginal](ActivityThread.java:6099)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.invokeOriginalMethodNative!(Native method)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.handleHookedMethod(XUtils.java:360)
    art/runtime/runtime.cc:423]   at android.app.ActivityThread.systemMain [XposedHooked](<Xposed>:-2)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.createSystemContext(SystemServer.java:434)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.run(SystemServer.java:353)
    art/runtime/runtime.cc:423]   at com.android.server.SystemServer.main(SystemServer.java:237)
    art/runtime/runtime.cc:423]   at java.lang.reflect.Method.invoke!(Native method)
    art/runtime/runtime.cc:423]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    art/runtime/runtime.cc:423]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
    art/runtime/runtime.cc:423]   at com.android.system.framework.XUtils.main(XUtils.java:102)
    art/runtime/runtime.cc:423] 
    art/runtime/runtime.cc:423] "Signal Catcher" prio=6 tid=2 WaitingInMainSignalCatcherLoop
10-26 16:49:20.451 2898-2898/? E/XUtils: /data/user_de/0/com.android.system.framework.installer/conf/modules.list`

**Comment by Massi-X** [comment]
You have to set the Xposed library to provided, not compile. You can close this.
