### ISSUE TITLE
Bootloops on Moto G4

### ISSUE THREAD

**Issue by scarlion1** [rovo89/Xposed#421]
I installed xposed-v90-sdk27-arm-beta3.zip on a Moto G4 with Android 8.1 and having bootloops now. The uninstaller worked and device is booting again. Any ideas to get xposed installed? How can I help?  Thanks

**Comment by scarlion1** [comment]
found the log file,

```
02-16 02:43:52.438 I/Xposed  (31762): -----------------

02-16 02:43:52.439 I/Xposed  (31762): Starting Xposed version 90-beta3, compiled for SDK 27

02-16 02:43:52.439 I/Xposed  (31762): Device: Moto G (4) (motorola), Android version 8.1.0 (SDK 27)

02-16 02:43:52.439 I/Xposed  (31762): ROM: n/a

02-16 02:43:52.439 I/Xposed  (31762): Build fingerprint: n/a

02-16 02:43:52.439 I/Xposed  (31762): Platform: armeabi-v7a, 32-bit binary, system server: yes

02-16 02:43:52.439 I/Xposed  (31762): SELinux enabled: yes, enforcing: yes

02-16 02:43:52.454 I/Xposed  (31762): -----------------

02-16 02:43:52.454 I/Xposed  (31762): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH

02-16 02:44:46.898 E/Xposed  (31762): Unable to open /vendor/framework/oat/arm to prepare apps for Xposed: Permission denied

02-16 02:44:50.754 I/Xposed  (31762): Detected ART runtime

02-16 02:44:50.756 I/Xposed  (31762): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing

02-16 02:44:50.955 E/Xposed  (31762): Errors during Xposed initialization

02-16 02:44:50.955 E/Xposed  (31762): java.lang.ExceptionInInitializerError

02-16 02:44:50.955 E/Xposed  (31762): 	at android.os.Build.-wrap2(Unknown Source:0)

02-16 02:44:50.955 E/Xposed  (31762): 	at android.os.Build$VERSION.<clinit>(Build.java:194)

02-16 02:44:50.955 E/Xposed  (31762): 	at 
android.content.res.ResourcesImpl.updateConfiguration(ResourcesImpl.java:445)

02-16 02:44:50.955 E/Xposed  (31762): 	at android.content.res.ResourcesImpl.<init>
(ResourcesImpl.java:170)

02-16 02:44:50.955 E/Xposed  (31762): 	at android.content.res.Resources.<init>
(Resources.java:247)

02-16 02:44:50.955 E/Xposed  (31762): 	at 
android.content.res.Resources.getSystem(Resources.java:180)

02-16 02:44:50.955 E/Xposed  (31762): 	at de.robv.android.xposed.XposedBridge.initXResources(XposedBridge.java:124)

02-16 02:44:50.955 E/Xposed  (31762): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:84)

02-16 02:44:50.955 E/Xposed  (31762): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference

02-16 02:44:50.955 E/Xposed  (31762): 	at android.os.Build.getBuildNumber(Build.java:1145)

02-16 02:44:50.955 E/Xposed  (31762): 	at android.os.Build.deriveFingerprint(Build.java:826)

02-16 02:44:50.955 E/Xposed  (31762): 	at android.os.Build.<clinit>(Build.java:812)

02-16 02:44:50.955 E/Xposed  (31762): 	... 8 more

```
Looks like permission denied on `/vendor/framework/oat/arm`

**Comment by Noshilyah** [comment]
Cx

**Comment by bsingpae22** [comment]
True
