### ISSUE TITLE
SettingsProvider classes not found, results in boot loop

### ISSUE THREAD

**Issue by xinluh** [rovo89/Xposed#53]
For device: 
```
I/Xposed  ( 7896): Starting Xposed version 67, compiled for SDK 21
I/Xposed  ( 7896): Device: 6045I (TCL ALCATEL ONETOUCH), Android version 5.0.2 (SDK 21)
I/Xposed  ( 7896): ROM: LRX22G release-keys
I/Xposed  ( 7896): Build fingerprint: TCL/6045I/idol3:5.0.2/LRX22G/v7SQR-0:user/release-keys
I/Xposed  ( 7896): Platform: arm64-v8a, 64-bit binary, system server: yes
I/Xposed  ( 7896): SELinux enabled: yes, enforcing: no
```

There seems to be something wrong with permission:
```
I/art     ( 8134): DexFile_isDexOptNeeded file /system/priv-app/SettingsProvider/arm64/SettingsProvider.odex needs to be recompiled with Xposed for /system/priv-app/SettingsProvider/SettingsProvider.apk
W/Binder  ( 8134): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 8134): java.lang.NullPointerException: Attempt to invoke interface method 'int android.app.IActivityManager.checkPermission(java.lang.String, int, int)' on a null object reference
W/Binder  ( 8134): 	at android.app.ContextImpl.checkPermission(ContextImpl.java:1905)
W/Binder  ( 8134): 	at android.app.ContextImpl.checkCallingOrSelfPermission(ContextImpl.java:1931)
W/Binder  ( 8134): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1968)
W/Binder  ( 8134): 	at com.android.server.power.PowerManagerService$BinderService.releaseWakeLock(PowerManagerService.java:2908)
W/Binder  ( 8134): 	at android.os.IPowerManager$Stub.onTransact(IPowerManager.java:94)
W/Binder  ( 8134): 	at android.os.Binder.execTransact(Binder.java:446)
W/ResourceType( 8204): CREATING STRING CACHE OF 56 bytes
W/ResourceType( 8204): CREATING STRING CACHE OF 1048 bytes
```
So eventually boot failed since essential services cannot find SettingsProvider: 
e.g.
```
W/ActivityManager( 7422): Can't addPackageDependency on system process
E/System  ( 7422): ******************************************
E/System  ( 7422): ************ Failure starting core service
E/System  ( 7422): java.lang.RuntimeException: Unable to get provider com.android.providers.settings.SettingsProvider: java.lang.ClassNotFoundException: Didn't find class "com.android.providers.settings.SettingsProvider" on path: DexPathList[[zip file "/system/priv-app/SettingsProvider/SettingsProvider.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
E/System  ( 7422): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5004)
E/System  ( 7422): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4596)
E/System  ( 7422): 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:5182)
E/System  ( 7422): 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:10292)
E/System  ( 7422): 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:504)
E/System  ( 7422): 	at com.android.server.SystemServer.run(SystemServer.java:281)
E/System  ( 7422): 	at com.android.server.SystemServer.main(SystemServer.java:195)
E/System  ( 7422): 	at java.lang.reflect.Method.invoke(Native Method)
E/System  ( 7422): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/System  ( 7422): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/System  ( 7422): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/System  ( 7422): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
E/System  ( 7422): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.providers.settings.SettingsProvider" on path: DexPathList[[zip file "/system/priv-app/SettingsProvider/SettingsProvider.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
E/System  ( 7422): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/System  ( 7422): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/System  ( 7422): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/System  ( 7422): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4989)
E/System  ( 7422): 	... 11 more
E/System  ( 7422): 	Suppressed: java.io.IOException: Entry not found
E/System  ( 7422): 		at dalvik.system.DexFile.openDexFileNative(Native Method)
E/System  ( 7422): 		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
E/System  ( 7422): 		at dalvik.system.DexFile.<init>(DexFile.java:80)
E/System  ( 7422): 		at dalvik.system.DexFile.<init>(DexFile.java:59)
E/System  ( 7422): 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:262)
E/System  ( 7422): 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:231)
E/System  ( 7422): 		at dalvik.system.DexPathList.<init>(DexPathList.java:109)
E/System  ( 7422): 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
E/System  ( 7422): 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
E/System  ( 7422): 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)
E/System  ( 7422): 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:361)
E/System  ( 7422): 		at de.robv.android.xposed.XposedBridge$4.afterHookedMethod(XposedBridge.java:240)
E/System  ( 7422): 		at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:664)
E/System  ( 7422): 		at android.app.LoadedApk.<init>(<Xposed>)
E/System  ( 7422): 		at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1752)
E/System  ( 7422): 		at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1713)
E/System  ( 7422): 		at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1685)
E/System  ( 7422): 		at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2174)
E/System  ( 7422): 		at android.app.ContextImpl.createPackageContext(ContextImpl.java:2161)
E/System  ( 7422): 		at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:658)
E/System  ( 7422): 		at android.app.ActivityThread.installProvider(ActivityThread.java:4974)
E/System  ( 7422): 		... 11 more
E/System  ( 7422): 	Caused by: java.io.IOException: Failed to open file '/data/dalvik-cache/arm64/system@priv-app@SettingsProvider@SettingsProvider.apk@classes.dex': Permission denied
E/System  ( 7422): 		... 32 more
E/System  ( 7422): 	Suppressed: java.lang.ClassNotFoundException: com.android.providers.settings.SettingsProvider
E/System  ( 7422): 		at java.lang.Class.classForName(Native Method)
E/System  ( 7422): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/System  ( 7422): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/System  ( 7422): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/System  ( 7422): 		... 13 more
E/System  ( 7422): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

How to fix this?

Full logcat: http://paste.ubuntu.com/11938673/

**Comment by xinluh** [comment]
Full logcat: http://paste.ubuntu.com/11938673/

**Comment by rovo89** [comment]
Thanks for the detailed report. One thing I noticed is that the system says that the odex file needs to be recompiled for Xposed, but there's no invocation of dex2oat afterwards. I'll have to have a closer look into this.

**Comment by xinluh** [comment]
I'm happy to provide more information or install test builds if you tell me what is needed.

**Comment by rovo89** [comment]
@xinluh Could you send me your /system/framework/arm/services.odex please?

**Comment by xinluh** [comment]
Here is /system/framework/arm/services.odex
https://www.dropbox.com/s/giraqcylczgizv0/services.odex?dl=0

**Comment by rovo89** [comment]
Could you test this please? https://www.dropbox.com/s/qahj2hed1e4rlez/xposed-v71-sdk21-arm-test2.zip?dl=0
If it's not working, please post a new logcat, otherwise just tell me it's ok.

**Comment by xinluh** [comment]
I would love to test, but I need the arm64 build, I think (installer error: Wrong platform: arm64, expected arm). 

Here is the services.odex from /system/framework/arm64, in case you need it:
https://www.dropbox.com/s/9xauzpalk1vcy8z/services64.odex?dl=0

**Comment by leloch** [comment]
Same here, unfortunately I need arm64 build as well.

**Comment by rovo89** [comment]
Here's the test build for arm64: https://www.dropbox.com/s/ilor9it1be7r6ec/xposed-v71-sdk21-arm64-test2.zip?dl=0

**Comment by xinluh** [comment]
Still boot loops with the same error of SettingsProvider not found, and there is still no dex2oat call after DexFile_isDexOptNeeded for SettingsProvider (in fact, for quite a few other packages, too, not sure if that is the expected behavior). Here is the full log:
http://paste.ubuntu.com/12087842/

I notice something funny with the build though. Initially a 32-bit binary is found: 
```
I/Xposed  (  396): Starting Xposed version 71 test2, compiled for SDK 21
I/Xposed  (  396): Device: 6045I (TCL ALCATEL ONETOUCH), Android version 5.0.2 (SDK 21)
I/Xposed  (  396): ROM: LRX22G release-keys
I/Xposed  (  396): Build fingerprint: TCL/6045I/idol3:5.0.2/LRX22G/v7SR4-0:user/release-keys
I/Xposed  (  396): Platform: arm64-v8a, 32-bit binary, system server: no
I/Xposed  (  396): SELinux enabled: yes, enforcing: yes
W/zygote  (  396): type=1400 audit(0.0:8): avc: denied { read } for name="input" dev="tmpfs" ino=7591 scontext=u:r:zygote:s0 tcontext=u:object_r:input_device:s0 tclass=dir permissive=0
I/Xposed  (  396): -----------------
E/Xposed  (  396): ERROR: Could not access Xposed jar '/system/framework/XposedBridge.jar'
```
but later the build becomes 64 bit:
```
I/Xposed  ( 2110): Starting Xposed version 71 test2, compiled for SDK 21
I/Xposed  ( 2110): Device: 6045I (TCL ALCATEL ONETOUCH), Android version 5.0.2 (SDK 21)
I/Xposed  ( 2110): ROM: LRX22G release-keys
I/Xposed  ( 2110): Build fingerprint: TCL/6045I/idol3:5.0.2/LRX22G/v7SR4-0:user/release-keys
I/Xposed  ( 2110): Platform: arm64-v8a, 64-bit binary, system server: yes
I/Xposed  ( 2110): SELinux enabled: yes, enforcing: yes
I/ServiceManager( 2128): Waiting for service user.xposed.system...
D/SRS_Spools_V2( 2109): DSEC_DMO_Token ERR: Unable to open key file. - /system/etc/srs/dts.lic
D/SRS_Spools_V2( 2109): DSEC_RET_Token ERR: Unable to open key file. - /system/etc/srs/dts.lic
D/SRS_Spools_V2( 2109): DSEC_DMO_Token ERR: Unable to open key file. - /system/etc/srs/dts.lic
D/SRS_Spools_V2( 2109): DSEC_RET_Token ERR: Unable to open key file. - /system/etc/srs/dts.lic
V/SRS_ProcT( 2109): TRUMEDIA_DSP_VERSION_STRING = v3.1.2.0
D/SRS_QDSP_Adapter( 2109): Control used - SRS TruMedia MI2S
W/SRS_QDSP_Adapter( 2109): Mixer opened 0xab0536d0
W/SRS_QDSP_Adapter( 2109): SRS TruMedia ctl opened 0xab0559cc
W/SRS_QDSP_Adapter( 2109): Not creating SRS DSP thread.
I/mediaserver( 2109): ServiceManager: 0xab05b800
I/AudioFlinger( 2109): Using default 3000 mSec as standby time.
I/ServiceManager( 2109): Waiting for service batterystats...
W/zygote64( 2110): type=1400 audit(0.0:9): avc: denied { read } for name="input" dev="tmpfs" ino=7591 scontext=u:r:zygote:s0 tcontext=u:object_r:input_device:s0 tclass=dir permissive=0
I/Xposed  ( 2110): -----------------
E/Xposed  ( 2110): ERROR: Could not access Xposed jar '/system/framework/XposedBridge.jar'
```

**Comment by rovo89** [comment]
Oh, I forgot that I had disabled flashing the XposedBridge.jar for my tests... Here are now builds:
https://www.dropbox.com/s/z34yoy7xawda2fl/xposed-v71-sdk21-arm-test3.zip?dl=0
https://www.dropbox.com/s/o5i89gq2h8yyk3d/xposed-v71-sdk21-arm64-test3.zip?dl=0

**Comment by xinluh** [comment]
The phone boots! It is taking a long time to optimize apps, so I'll report back when everything loads up.

**Comment by leloch** [comment]
I can confirm letv also boots with test3 version!

**Comment by sansanca** [comment]
Guys, i'm running LeTV x600 with version 4S. Rovo do you have an uninstaller for this v71 build?

**Comment by sansanca** [comment]
All right, i just checked the uninstaller in xda forum, seems version agnostic, so i'm going to try this build now!

**Comment by sansanca** [comment]
And it booted! First it optimized 170 apps, then 55, 35 and then 17(?!). Oh man... this would be so great if GravityBox worked on this!

**Comment by sansanca** [comment]
Gravity for Lollipop installed and seems to be working, i mean, at least it changed some battery text on the status bar! This is great. However doing a TWRP backup right now just in case some stuff goes nuts.

Thanks Rovo!

**Comment by viperboy** [comment]
I modified your xposed.prop since I'm on 5.1.1, as I got the maxsdk error. Not surprisingly, it didn't boot on my G Stylo, not even past the T-Mobile splash screen that then goes to LiveBoot. Wiped cache and dalvik after the flash as well. However, your changes might be good for romracer and his unofficial 5.1 builds, that would get Xposed working on many of the current LG devices, including the G4. 

Can I ask what you found out from all of our services.odex files and what you've changed in xposed? I love the technical details!

**Comment by rovo89** [comment]
The commit message contains many details. Feel free to ask if anything is still unclear. I asked for the services.odex files because I thought I had identified a possible cause, but then I realized it must be something else.

**Comment by rovo89** [comment]
@xinluh @leloch @sansanca or anyone else who is running a stock ROM on an affected LeTV or LG device: I recently made some changes which might affect your device. To ensure that Xposed still works, I'd like to have some testers.

For those who want to test: https://www.dropbox.com/sh/gketc1pry8ovy33/AACEqJME6LijmlFzrRlkAnwja?dl=0
There are two test zips for every Android version/platform combination. Please first flash test1, clear the Dalvik cache and reboot. There might be a boot loop, but please give it at least 10 minutes. Then please repeat the exact same procedure with test2. Please report here which device and ROM you're using and whether versions test1 and/or test2 worked for you. Thanks!
