### ISSUE TITLE
Bootloop on LG G Stylo

### ISSUE THREAD

**Issue by viperboy** [rovo89/Xposed#56]
Device Info:
```
I/Xposed  (10905): Starting Xposed version 70 (by romracer / 20150808), compiled for SDK 22

I/Xposed  (10905): Device: LG-H631 (LGE), Android version 5.1.1 (SDK 22)

I/Xposed  (10905): ROM: LMY47V

I/Xposed  (10905): Build fingerprint: lge/g4stylusn_tmo_us/g4stylusn:5.1.1/LMY47V/15167172282f1:user/release-keys

I/Xposed  (10905): Platform: armeabi-v7a, 32-bit binary, system server: yes

I/Xposed  (10905): SELinux enabled: yes, enforcing: yes
```

This device is on 5.1.1 and I was fully aware this would likely not work on the latest framework, even with your recent LG fixes, as it's constantly reported that this doesn't boot on the G4. I didn't see an open issue about this specific LG issue, so I wanted to open this to try and help debug this since it seems like no one has given you anything useful to work with. I've tried your version of Xposed as well as an unofficial version here: http://forum.xda-developers.com/xposed/super-alpha-posted-permission-xposed-t3072979

Flashed and cleared cache and dalvik. Waited for a bit, used LiveBoot by Chainfire to see that it was indeed freaking out on booting. Captured a log, found the following information:

```
E/System  ( 3096): ************ Failure starting core service

E/System  ( 3096): java.lang.RuntimeException: Unable to get provider com.android.providers.settings.SettingsProvider: java.lang.ClassNotFoundException: Didn't find class "com.android.providers.settings.SettingsProvider" on path: DexPathList[[zip file "/system/framework/com.lge.mdm.jar", zip file "/system/priv-app/LGSettingsProvider/LGSettingsProvider.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

E/System  ( 3096): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5150)

E/System  ( 3096): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4742)

E/System  ( 3096): 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:5344)

E/System  ( 3096): 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:10445)

E/System  ( 3096): 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:479)

E/System  ( 3096): 	at com.android.server.SystemServer.run(SystemServer.java:271)

E/System  ( 3096): 	at com.android.server.SystemServer.main(SystemServer.java:185)

E/System  ( 3096): 	at java.lang.reflect.Method.invoke(Native Method)

E/System  ( 3096): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/System  ( 3096): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)

E/System  ( 3096): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

E/System  ( 3096): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)

E/System  ( 3096): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.providers.settings.SettingsProvider" on path: DexPathList[[zip file "/system/framework/com.lge.mdm.jar", zip file "/system/priv-app/LGSettingsProvider/LGSettingsProvider.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

E/System  ( 3096): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

E/System  ( 3096): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

E/System  ( 3096): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

E/System  ( 3096): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5135)

E/System  ( 3096): 	... 11 more

E/System  ( 3096): 	Suppressed: java.io.IOException: Entry not found

E/System  ( 3096): 		at dalvik.system.DexFile.openDexFileNative(Native Method)

E/System  ( 3096): 		at dalvik.system.DexFile.openDexFile(DexFile.java:295)

E/System  ( 3096): 		at dalvik.system.DexFile.<init>(DexFile.java:80)

E/System  ( 3096): 		at dalvik.system.DexFile.<init>(DexFile.java:59)

E/System  ( 3096): 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:262)

E/System  ( 3096): 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:231)

E/System  ( 3096): 		at dalvik.system.DexPathList.<init>(DexPathList.java:109)

E/System  ( 3096): 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)

E/System  ( 3096): 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)

E/System  ( 3096): 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)

E/System  ( 3096): 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:414)

E/System  ( 3096): 		at de.robv.android.xposed.XposedBridge$4.afterHookedMethod(XposedBridge.java:240)

E/System  ( 3096): 		at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:664)

E/System  ( 3096): 		at android.app.LoadedApk.<init>(<Xposed>)

E/System  ( 3096): 		at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1812)

E/System  ( 3096): 		at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1773)

E/System  ( 3096): 		at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1745)

E/System  ( 3096): 		at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2318)

E/System  ( 3096): 		at android.app.ContextImpl.createPackageContext(ContextImpl.java:2305)

E/System  ( 3096): 		at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:671)

E/System  ( 3096): 		at android.app.ActivityThread.installProvider(ActivityThread.java:5120)

E/System  ( 3096): 		... 11 more

E/System  ( 3096): 	Caused by: java.io.IOException: Failed to open file '/data/dalvik-cache/arm/system@priv-app@LGSettingsProvider@LGSettingsProvider.apk@classes.dex': Permission denied

E/System  ( 3096): 		... 32 more

E/System  ( 3096): 	Suppressed: java.lang.ClassNotFoundException: com.android.providers.settings.SettingsProvider

E/System  ( 3096): 		at java.lang.Class.classForName(Native Method)

E/System  ( 3096): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)

E/System  ( 3096): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)

E/System  ( 3096): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

E/System  ( 3096): 		... 13 more

E/System  ( 3096): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

I pulled both /system/framework/com.lge.mdm.jar and /system/priv-app/LGSettingsProvider/LGSettingsProvider.apk, available here: https://db.tt/y8EFBWQr

com.lge.mdm.jar is 1kb with only a META-INF in it (that's all I see with 7zip and JD-GUI), is this related to LG's encrypted apps at all? I wasn't able to see the smali code when I decompiled LGSettingsProvider with the latest apktool, it just didn't exist, so I was thinking maybe it dealt with LG encrypting these apps or something. 

Is there anything else you need or anything I can test? I'm happy to check out anything.

Thanks for your time and the work you dedicate to this project!

EDIT: Found that there was a similar, yet different, issue reported for the OneTouch: https://github.com/rovo89/Xposed/issues/53 Interesting to see something similar happening on a different version of Android, different phone, etc so maybe this will help.

**Comment by rovo89** [comment]
Yes, this is indeed the same issue as in #53 and #50. If you could send me your /system/framework/arm/services.odex, that would be helpful. Anyway, I close this issue to keep things concentrated in one place.

**Comment by viperboy** [comment]
I'm not sure where you want this since you closed this, but here is services.odex:

https://db.tt/3wvgo1ss

**Comment by viperboy** [comment]
Also, I'm a Software Engineer myself, I'd be curious what the technical issue is and I'm happy to test whatever you need.

**Comment by rovo89** [comment]
Thanks, can you test this please? https://github.com/rovo89/Xposed/issues/53#issuecomment-131349505
