### ISSUE TITLE
Google keyboard crashes in the play store

### ISSUE THREAD

**Issue by pgera** [rovo89/Xposed#69]
I'm using xposed (v74) on a nexus 5 with 5.1. I get a  "google keyboard has crashed" quite often when I install or update apps from the google play store. I see this in the logs:

```
------ SYSTEM LOG (logcat -v threadtime -d *:v) ------
--------- beginning of crash
09-28 02:41:27.136  1180  1180 E AndroidRuntime: FATAL EXCEPTION: main
09-28 02:41:27.136  1180  1180 E AndroidRuntime: Process: com.google.android.inputmethod.latin, PID: 1180
09-28 02:41:27.136  1180  1180 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.andrewshu.android.reddit flg=0x4000010 (has extras) } in com.android.inputmethod.latin.DictionaryPackInstallBroadcastReceiver@fa1b527
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:876)
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:135)
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5254)
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Method.java:372)
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
09-28 02:41:27.136  1180  1180 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.ProviderInfo.authority' on a null object reference
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at com.android.inputmethod.latin.DictionaryPackInstallBroadcastReceiver.onReceive(DictionaryPackInstallBroadcastReceiver.java:91)
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:866)
09-28 02:41:27.136  1180  1180 E AndroidRuntime:        ... 9 more
```

I'm not sure if an xposed module or the framework itself has a part to play, but "de.robv.android.xposed.XposedBridge.main" is the only helpful thing I see in the log.

**Comment by rovo89** [comment]
I see no relation to Xposed here. You will find XposedBridge.main in *every* stack trace when Xposed is installed. That's a method called very early when the device boots though, it's not involved in the crash.

I close this issue now - feel free to reopen if you have more indicators that this is related to Xposed (e.g. you don't have these crashes when Xposed is uninstalled, but they occur if it's installed, even without any active modules).
